"""
Seed data for the bank directory and the curated corridor rules.

This is intentionally a STARTER set — real production uses SWIFTRef / Accuity
Bankers Almanac for authoritative BIC data and correspondent relationships.
The corridor rules below reflect commonly known correspondent patterns for
major corridors; treat confidence levels as advisory.
"""
from ..models import Account, Bank, CorridorRule, SSI

# (bic, bank_name, country_code, city, country_currency)
BANKS = [
    # ---- major global correspondents (USD/EUR/GBP clearing) ----
    ("CITIUS33XXX", "Citibank N.A.", "US", "New York", "USD"),
    ("BOFAUS3NXXX", "Bank of America", "US", "Charlotte", "USD"),
    ("CHASUS33XXX", "JPMorgan Chase", "US", "New York", "USD"),
    ("BNYMUS33XXX", "BNY Mellon", "US", "New York", "USD"),
    ("COBADEFFXXX", "Commerzbank", "DE", "Frankfurt", "EUR"),
    ("DEUTDEFFXXX", "Deutsche Bank", "DE", "Frankfurt", "EUR"),
    ("BNPAFRPPXXX", "BNP Paribas", "FR", "Paris", "EUR"),
    ("SOGEFRPPXXX", "Societe Generale", "FR", "Paris", "EUR"),
    ("ABNANL2AXXX", "ABN AMRO", "NL", "Amsterdam", "EUR"),
    ("BARCGB22XXX", "Barclays", "GB", "London", "GBP"),
    ("NWBKGB2LXXX", "NatWest", "GB", "London", "GBP"),
    ("HSBCGB22XXX", "HSBC UK", "GB", "Birmingham", "GBP"),
    ("SCBLGB22XXX", "Standard Chartered", "GB", "London", "GBP"),
    # ---- Africa (destinations) ----
    ("GTBINGLAXXX", "Guaranty Trust Bank", "NG", "Lagos", "NGN"),
    ("DBLNNGLAXXX", "Diamond Bank", "NG", "Lagos", "NGN"),
    ("ZENINGLAXXX", "Zenith Bank", "NG", "Lagos", "NGN"),
    ("SBICUS44XXX", "Standard Bank of South Africa (NY branch)", "US", "New York", "ZAR"),
    ("SBICZAJJXXX", "Standard Bank", "ZA", "Johannesburg", "ZAR"),
    ("SCBLKENXAXX", "Standard Chartered Kenya", "KE", "Nairobi", "KES"),
    ("ECOCGHACXXX", "Ecobank Ghana", "GH", "Accra", "GHS"),
    # ---- Asia-Pacific (destinations) ----
    ("BOTKJPJTXXX", "Bank of Tokyo-Mitsubishi UFJ (MUFG)", "JP", "Tokyo", "JPY"),
    ("SMBCJPJTXXX", "Sumitomo Mitsui Banking Corp (SMBC)", "JP", "Tokyo", "JPY"),
    ("BKCHCNBJXXX", "Bank of China", "CN", "Beijing", "CNY"),
    ("ICBKCNBJXXX", "Industrial & Commercial Bank of China (ICBC)", "CN", "Beijing", "CNY"),
    ("COMMCNSHXXX", "China Construction Bank", "CN", "Shanghai", "CNY"),
    ("HSBCHKHHXXX", "HSBC Hong Kong", "HK", "Hong Kong", "HKD"),
    ("BKCHHKHHXXX", "Bank of China Hong Kong", "HK", "Hong Kong", "HKD"),
    ("DBSSSGSXAXX", "DBS Bank Singapore", "SG", "Singapore", "SGD"),
    ("OCBCSGSXAXX", "OCBC Bank", "SG", "Singapore", "SGD"),
    ("UOVBSGSGXXX", "United Overseas Bank (UOB)", "SG", "Singapore", "SGD"),
    ("ANZBAU3MXXX", "ANZ Bank", "AU", "Melbourne", "AUD"),
    ("NATAAU33XXX", "National Australia Bank (NAB)", "AU", "Melbourne", "AUD"),
    ("CTBAAU2SXXX", "Commonwealth Bank of Australia", "AU", "Sydney", "AUD"),
    ("ANZBNZ22XXX", "ANZ Bank New Zealand", "NZ", "Auckland", "NZD"),
    ("ASBBNZ2AXXX", "ASB Bank", "NZ", "Auckland", "NZD"),
    ("BNINIDJAXXX", "Bank Negara Indonesia", "ID", "Jakarta", "IDR"),
    ("BNIAIDJAXXX", "Bank Central Asia (BCA)", "ID", "Jakarta", "IDR"),
    ("MBBEMYKLXXX", "Maybank", "MY", "Kuala Lumpur", "MYR"),
    ("CIBBMYKLXXX", "CIMB Bank", "MY", "Kuala Lumpur", "MYR"),
    ("BKKBTHBKXXX", "Bangkok Bank", "TH", "Bangkok", "THB"),
    ("KASITHBKXXX", "Kasikornbank", "TH", "Bangkok", "THB"),
    ("ICBVVNVXXXX", "Vietcombank", "VN", "Hanoi", "VND"),
    ("CITYBDDHXXX", "Citibank Bangladesh", "BD", "Dhaka", "BDT"),
    ("HABBPKKAAXX", "Habib Bank", "PK", "Karachi", "PKR"),
    ("UNILPKKAXXX", "UBL", "PK", "Karachi", "PKR"),
    # ---- Middle East (destinations) ----
    ("EBILAEADXXX", "Emirates NBD", "AE", "Dubai", "AED"),
    ("NRBMAEADXXX", "Mashreq Bank", "AE", "Dubai", "AED"),
    ("NCBKSAJEXXX", "Saudi National Bank (SNB)", "SA", "Riyadh", "SAR"),
    ("RJHISARIXXX", "Al Rajhi Bank", "SA", "Riyadh", "SAR"),
    ("SAMBSARIXXX", "Samba / FAB Saudi", "SA", "Riyadh", "SAR"),
    ("NBQAQAQAXXX", "Qatar National Bank (QNB)", "QA", "Doha", "QAR"),
    ("DOHAQAQAXXX", "Doha Bank", "QA", "Doha", "QAR"),
    ("NBOMKWKEXXX", "National Bank of Kuwait (NBK)", "KW", "Kuwait City", "KWD"),
    ("NBOFBHBMXXX", "National Bank of Bahrain", "BH", "Manama", "BHD"),
    ("NBOOOMRXXXX", "National Bank of Oman", "OM", "Muscat", "OMR"),
    ("JGBAJOA0XXX", "Jordan Kuwait Bank", "JO", "Amman", "JOD"),
    ("POALILITXXX", "Bank Hapoalim", "IL", "Tel Aviv", "ILS"),
    ("LUMIILITXXX", "Bank Leumi", "IL", "Tel Aviv", "ILS"),
    ("TGBTTR2IXXX", "Garanti BBVA", "TR", "Istanbul", "TRY"),
    ("ISBKTRISXXX", "Isbank", "TR", "Istanbul", "TRY"),
    ("ZKBATR2SXXX", "Ziraat Bankasi", "TR", "Ankara", "TRY"),
    # ---- Asia ----
    ("HDFCINBBXXX", "HDFC Bank", "IN", "Mumbai", "INR"),
    ("ICICINBBXXX", "ICICI Bank", "IN", "Mumbai", "INR"),
    ("SBININBBXXX", "State Bank of India", "IN", "Mumbai", "INR"),
    # ---- Additional correspondent + destination banks (from SSI research) ----
    # Global correspondents seen in published SSIs
    ("SCBLUS33XXX", "Standard Chartered Bank New York", "US", "New York", "USD"),
    ("IRVTUS3NXXX", "Bank of New York Mellon", "US", "New York", "USD"),
    ("CITIIE2XXXX", "Citibank Europe Plc", "IE", "Dublin", "EUR"),
    ("BBRUBEBBXXX", "ING Belgium", "BE", "Brussels", "EUR"),
    ("CCFRFRPPXXX", "HSBC France", "FR", "Paris", "EUR"),
    ("SCBLDEFXXXX", "Standard Chartered Germany", "DE", "Frankfurt", "EUR"),
    ("SCBLGB2LXXX", "Standard Chartered London", "GB", "London", "GBP"),
    ("SCBLHKHHXXX", "Standard Chartered Hong Kong", "HK", "Hong Kong", "HKD"),
    ("SCBLSGSGXXX", "Standard Chartered Singapore", "SG", "Singapore", "SGD"),
    ("SCBLBDDXXXX", "Standard Chartered Bangladesh", "BD", "Dhaka", "BDT"),
    ("SCBLPKKXXXX", "Standard Chartered Pakistan", "PK", "Karachi", "PKR"),
    # Country clearing banks (from published SSIs)
    ("CBAUAEAAXXX", "Central Bank of the UAE", "AE", "Abu Dhabi", "AED"),
    ("ROYCCAT2XXX", "Royal Bank of Canada", "CA", "Toronto", "CAD"),
    ("CIBCCATTXXX", "CIBC", "CA", "Toronto", "CAD"),
    ("BOFMCAM2XXX", "Bank of Montreal", "CA", "Toronto", "CAD"),
    ("UBSWCHZH80A", "UBS Switzerland", "CH", "Zurich", "CHF"),
    ("DABADKKKXXX", "Danske Bank", "DK", "Copenhagen", "DKK"),
    ("ESSESESSXXX", "Skandinaviska Enskilda Banken", "SE", "Stockholm", "SEK"),
    ("DNBANOKKXXX", "DNB Bank ASA", "NO", "Oslo", "NOK"),
    ("MHCBJPJTXXX", "Mizuho Bank", "JP", "Tokyo", "JPY"),
    ("NBOKKWKWXXX", "National Bank of Kuwait", "KW", "Kuwait City", "KWD"),
    ("ARABJOAXXXX", "Arab Bank plc", "JO", "Amman", "JOD"),
    ("QNBAQAQAXXX", "Qatar National Bank", "QA", "Doha", "QAR"),
    ("BCMAMAMCXXX", "Attijariwafa Bank", "MA", "Casablanca", "MAD"),
    ("BBKUBHBMXXX", "BBK Bahrain", "BH", "Manama", "BHD"),
    ("BMUSOMRXXXX", "BankMuscat", "OM", "Seeb", "OMR"),
    ("BSHROMRUXXX", "Sohar International Bank", "OM", "Muscat", "OMR"),
    ("FIRNZAJJXXX", "FirstRand Bank", "ZA", "Johannesburg", "ZAR"),
    # Destination banks with published SSIs
    ("BDINIDJAXXX", "Bank Danamon", "ID", "Jakarta", "IDR"),
    ("BCEYLKLXXXX", "Bank of Ceylon", "LK", "Colombo", "LKR"),
    ("HBLILKLXXXX", "Hatton National Bank", "LK", "Colombo", "LKR"),
    ("EBILEGCXXXX", "Emirates NBD Egypt", "EG", "Cairo", "EGP"),
    ("EBILSARIXXX", "Emirates NBD Saudi", "SA", "Riyadh", "SAR"),
    ("DEUTCZPXXXX", "Deutsche Bank Czech Republic", "CZ", "Prague", "CZK"),
    # ---- SMBC and its correspondents (from SMBC published SSI page) ----
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "GB", "London", "GBP"),
    ("SMBCUS33XXX", "SMBC New York", "US", "New York", "USD"),
    ("SMBCHKHHXXX", "SMBC Hong Kong", "HK", "Hong Kong", "HKD"),
    ("SMBCSGSGXXX", "SMBC Singapore", "SG", "Singapore", "SGD"),
    ("SMBCTHBKXXX", "SMBC Bangkok", "TH", "Bangkok", "THB"),
    ("SMBCINDDXXX", "SMBC New Delhi", "IN", "New Delhi", "INR"),
    ("ADCBAEAAXXX", "Abu Dhabi Commercial Bank", "AE", "Abu Dhabi", "AED"),
    ("BCMRMXMMCOR", "BBVA Bancomer SA Mexico", "MX", "Mexico City", "MXN"),
    ("BKNZNZ22XXX", "Bank of New Zealand", "NZ", "Wellington", "NZD"),
    ("BPKOPLPWXXX", "PKO Bank Polski SA", "PL", "Warsaw", "PLN"),
    ("CEKOCZPPXXX", "Ceskoslovenska Obchodni Banka", "CZ", "Prague", "CZK"),
    ("GULBKWKWXXX", "Gulf Bank KSC Kuwait", "KW", "Kuwait City", "KWD"),
    ("HANDSESSXXX", "Svenska Handelsbanken AB", "SE", "Stockholm", "SEK"),
    ("OTPVHUHBXXX", "OTP Bank Ltd Budapest", "HU", "Budapest", "HUF"),
    ("RIBLSARIXXX", "Riyad Bank Riyadh", "SA", "Riyadh", "SAR"),
    ("RNCBROBUXXX", "Romanian Commercial Bank Bucharest", "RO", "Bucharest", "RON"),
    ("TGBATRISXXX", "Turkiye Garanti Bankasi AS Istanbul", "TR", "Istanbul", "TRY"),
    ("ABSAZAJJXXX", "Absa Bank Ltd Johannesburg", "ZA", "Johannesburg", "ZAR"),
    # ---- State Bank of India branches (from Bank of Maharashtra SSI) ----
    ("SBINAU2SXXX", "State Bank of India Sydney", "AU", "Sydney", "AUD"),
    ("SBINSGSXXXX", "State Bank of India Singapore", "SG", "Singapore", "SGD"),
    ("STADDEFFXXX", "State Bank of India Frankfurt", "DE", "Frankfurt", "EUR"),
    ("STADGB2LXXX", "State Bank of India London", "GB", "London", "GBP"),
    # ---- Bank of Maharashtra (destination) ----
    ("MAHBBINPXXX", "Bank of Maharashtra", "IN", "Pune", "INR"),
    # ---- Deutsche Bank branches (from DB Prague SSI, Nov 2025) ----
    ("DEUTGB2LXXX", "Deutsche Bank AG London", "GB", "London", "GBP"),
    ("DEUTCHZHXXX", "Deutsche Bank AG Zurich", "CH", "Zurich", "CHF"),
    ("DEUTJPJTXXX", "Deutsche Bank AG Tokyo", "JP", "Tokyo", "JPY"),
    ("DEUTCAFFXXX", "Deutsche Bank AG Toronto", "CA", "Toronto", "CAD"),
    ("DEUTAU2SXXX", "Deutsche Bank AG Sydney", "AU", "Sydney", "AUD"),
    ("DEUTSESSXXX", "Deutsche Bank AG Stockholm", "SE", "Stockholm", "SEK"),
    ("DEUTNOKKXXX", "Deutsche Bank AG Oslo", "NO", "Oslo", "NOK"),
    ("DEUTPLPKXXX", "Deutsche Bank Polska SA", "PL", "Warsaw", "PLN"),
    ("DEUTHUHBXXX", "Deutsche Bank AG Budapest", "HU", "Budapest", "HUF"),
    ("BKTRUS33XXX", "Deutsche Bank Trust Company Americas", "US", "New York", "USD"),
    # ---- YES Bank (destination) ----
    ("YESBINBBXXX", "YES Bank Ltd", "IN", "Mumbai", "INR"),
    # ---- U.S. Bank ----
    ("USBKUS44XXX", "U.S. Bank National Association", "US", "Minneapolis", "USD"),
    ("NBCBGB2LXXX", "U.S. Bank London", "GB", "London", "GBP"),
    # ---- Nordea + Lloyds + DBS (from Saxo Bank SSI) ----
    ("NADADKKKXXX", "Nordea Bank Danmark", "DK", "Copenhagen", "DKK"),
    ("NDEAFIHHXXX", "Nordea Bank Finland", "FI", "Helsinki", "EUR"),
    ("LOYDGB2LXXX", "Lloyds Banking Group", "GB", "London", "GBP"),
    # ---- Access Bank Nigeria (destination) ----
    ("ABNGNGLAXXX", "Access Bank Plc", "NG", "Lagos", "NGN"),
    # ---- Saxo Bank Denmark (destination) ----
    ("SAXODK22XXX", "Saxo Bank A/S", "DK", "Copenhagen", "DKK"),
    # ---- MUFG branches + correspondents (from MUFG EMEA SSI page) ----
    ("BOTKGB2LXXX", "MUFG Bank Ltd London", "GB", "London", "GBP"),
    ("BOTKAU2XXXX", "MUFG Bank Ltd Sydney", "AU", "Sydney", "AUD"),
    ("BOTKCATXXXX", "MUFG Bank Ltd Toronto", "CA", "Toronto", "CAD"),
    ("BOTKHKHHXXX", "MUFG Bank Ltd Hong Kong", "HK", "Hong Kong", "HKD"),
    ("BOTKINDDXXX", "MUFG Bank Ltd New Delhi", "IN", "New Delhi", "INR"),
    ("BOTKMXMXXXX", "MUFG Bank SA Mexico City", "MX", "Mexico City", "MXN"),
    ("BOTKMYKXXXX", "MUFG Bank Malaysia Kuala Lumpur", "MY", "Kuala Lumpur", "MYR"),
    ("BOTKSGSXXXX", "MUFG Bank Ltd Singapore", "SG", "Singapore", "SGD"),
    ("BOTKTHBXXXX", "Bank of Ayudhya Bangkok", "TH", "Bangkok", "THB"),
    ("BOTKUS33XXX", "MUFG Bank Ltd New York", "US", "New York", "USD"),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "NL", "Amsterdam", "EUR"),
    ("BACXHUHBXXX", "UniCredit Bank Hungary Budapest", "HU", "Budapest", "HUF"),
    ("BACXROBUXXX", "UniCredit Bank SA Bucharest", "RO", "Bucharest", "RON"),
    ("CITIPLPXXXX", "Bank Handlowy Warsaw", "PL", "Warsaw", "PLN"),
    ("HSBKKZKXXXX", "Halyk Bank Kazakhstan Almaty", "KZ", "Almaty", "KZT"),
    ("SBZAZAJJXXX", "Standard Bank South Africa Johannesburg", "ZA", "Johannesburg", "ZAR"),
    # ---- ICICI Bank UK PLC (destination) ----
    ("ICICGB2LXXX", "ICICI Bank UK PLC", "GB", "London", "GBP"),
    # ---- SBI branches (from SBI Nostro SSI PDF) ----
    ("SBINGB2LXXX", "State Bank of India London", "GB", "London", "GBP"),
    ("SBINJPJTXXX", "State Bank of India Tokyo", "JP", "Tokyo", "JPY"),
    ("SBINHKHHXXX", "State Bank of India Hong Kong", "HK", "Hong Kong", "HKD"),
    ("SBINSGSGXXX", "State Bank of India Singapore", "SG", "Singapore", "SGD"),
    ("SBINUS33XXX", "State Bank of India New York", "US", "New York", "USD"),
    ("SBINUS64XXX", "State Bank of India Chicago", "US", "Chicago", "USD"),
    ("SBINUS66XXX", "State Bank of India Los Angeles", "US", "Los Angeles", "USD"),
    ("SBINZAJJXXX", "State Bank of India Johannesburg", "ZA", "Johannesburg", "ZAR"),
    ("SBINBHBMXXX", "State Bank of India Bahrain", "BH", "Manama", "BHD"),
    ("SBINBE2XXXX", "State Bank of India Antwerp", "BE", "Antwerp", "EUR"),
    ("SBINCATXXXX", "State Bank of India Toronto", "CA", "Toronto", "CAD"),
    # ---- SBI correspondents (new banks from SBI nostro list) ----
    ("CHASGB2LXXX", "JP Morgan Chase London", "GB", "London", "GBP"),
    ("BARCKENXXXX", "Barclays Bank Kenya", "KE", "Nairobi", "KES"),
    ("BBVAESMMXXX", "BBVA Madrid", "ES", "Madrid", "EUR"),
    ("BCITITMMXXX", "Intesa Sanpaolo Milan", "IT", "Milan", "EUR"),
    ("BNLIITRRXXX", "Banca Nazionale del Lavoro Rome", "IT", "Rome", "EUR"),
    ("UNCRITMMXXX", "Unicredito Italiano Milan", "IT", "Milan", "EUR"),
    ("VRBPIT2VXXX", "Banca Popolare di Verona", "IT", "Verona", "EUR"),
    ("RBOSNL2AXXX", "Royal Bank of Scotland Amsterdam", "NL", "Amsterdam", "EUR"),
    ("RZBAATWWXXX", "Raiffeisen Zentralbank Vienna", "AT", "Vienna", "EUR"),
    ("HKBCCATTXXX", "HSBC Bank Canada Toronto", "CA", "Toronto", "CAD"),
    ("BOFACATTXXX", "Bank of America Toronto", "CA", "Toronto", "CAD"),
    ("BOFAHKHXXXX", "Bank of America Hong Kong", "HK", "Hong Kong", "HKD"),
    ("BOFASG2XXXX", "Bank of America Singapore", "SG", "Singapore", "SGD"),
    ("BOFACH2XXXX", "Bank of America Switzerland", "CH", "Zurich", "CHF"),
    ("BOMLAEADXXX", "Mashreqbank UAE", "AE", "Dubai", "AED"),
    ("SCBLAEADXXX", "Standard Chartered Dubai", "AE", "Dubai", "AED"),
    ("SCBLJPJTXXX", "Standard Chartered Tokyo", "JP", "Tokyo", "JPY"),
    ("SCBLCNSXSHA", "Standard Chartered China Shanghai", "CN", "Shanghai", "CNY"),
    ("NBADAEAAXXX", "National Bank of Abu Dhabi", "AE", "Abu Dhabi", "AED"),
    ("CRESCHZZ80A", "Credit Suisse Zurich", "CH", "Zurich", "CHF"),
    ("ZKBKCHZZ80A", "Zurcher Kantonalbank Zurich", "CH", "Zurich", "CHF"),
    ("WPACAU2SXXX", "Westpac Sydney", "AU", "Sydney", "AUD"),
    ("WPACNZ2WXXX", "Westpac Wellington", "NZ", "Wellington", "NZD"),
    # ---- Federal Bank India (destination) ----
    ("FDRLINBBIBD", "Federal Bank Ltd", "IN", "Aluva", "INR"),
    # ---- Deutsche Bank branches (from DB Seoul SSI, Mar 2025) ----
    ("DEUTKRSXXXX", "Deutsche Bank AG Seoul", "KR", "Seoul", "KRW"),
    ("DEUTHKHHXXX", "Deutsche Bank AG Hong Kong", "HK", "Hong Kong", "HKD"),
    ("DEUTSGSGXXX", "Deutsche Bank AG Singapore", "SG", "Singapore", "SGD"),
    ("DEUTTHBKXXX", "Deutsche Bank AG Bangkok", "TH", "Bangkok", "THB"),
    ("DEUTNZ2AXXX", "Deutsche Bank AG Wellington", "NZ", "Wellington", "NZD"),
    ("DEUTDKKKXXX", "Deutsche Bank AG Copenhagen", "DK", "Copenhagen", "DKK"),
    ("DEUTTWTWXXX", "Deutsche Bank AG Taipei", "TW", "Taipei", "TWD"),
    ("DEUTINBBXXX", "Deutsche Bank AG India", "IN", "Mumbai", "INR"),
    ("DEUTCNSHXXX", "Deutsche Bank AG China Shanghai", "CN", "Shanghai", "CNY"),
    # ---- State Street + BNY Mellon + SCB Australia (from EDB SSI) ----
    ("SBOSGB2LXXX", "State Street Bank London", "GB", "London", "GBP"),
    ("IRVTBE99XXX", "BNY Mellon Brussels", "BE", "Brussels", "EUR"),
    ("IRVTJPJTXXX", "BNY Mellon Japan", "JP", "Tokyo", "JPY"),
    ("SCBLAU2SXXX", "Standard Chartered Australia", "AU", "Sydney", "AUD"),
    # ---- European Depositary Bank (destination) ----
    ("EDBBEB22XXX", "European Depositary Bank SA", "LU", "Luxembourg", "EUR"),
    # ---- Global IME Bank + Mashreqbank NY (from Global IME SSI page) ----
    ("GLBBNPKAXXX", "Global IME Bank Ltd", "NP", "Kathmandu", "NPR"),
    ("BOMLUS33XXX", "Mashreqbank NY", "US", "New York", "USD"),
    # ---- TMB Bank India (destination) ----
    ("TMBLINDIXXX", "Tamilnad Mercantile Bank", "IN", "Tuticorin", "INR"),
    # ---- IDFC FIRST Bank India (destination) ----
    ("IDFBINBBXXX", "IDFC FIRST Bank", "IN", "Mumbai", "INR"),
]

# (destination_currency, destination_country, intermediary_bic,
#  intermediary_name, corridor, confidence, rank)
CORRIDOR_RULES = [
    # USD -> Nigeria
    ("NGN", "NG", "CITIUS33XXX", "Citibank N.A.", "USD->NG", "high", 1),
    ("NGN", "NG", "BOFAUS3NXXX", "Bank of America", "USD->NG", "medium", 2),
    ("NGN", "NG", "SCBLGB22XXX", "Standard Chartered", "USD->NG", "medium", 3),
    # USD -> Kenya
    ("KES", "KE", "CITIUS33XXX", "Citibank N.A.", "USD->KE", "high", 1),
    ("KES", "KE", "SCBLGB22XXX", "Standard Chartered", "USD->KE", "high", 2),
    # USD -> Ghana
    ("GHS", "GH", "CITIUS33XXX", "Citibank N.A.", "USD->GH", "high", 1),
    ("GHS", "GH", "ECOCGHACXXX", "Ecobank Ghana", "USD->GH", "medium", 2),
    # USD/ZAR -> South Africa
    ("ZAR", "ZA", "SBICUS44XXX", "Standard Bank (NY)", "USD->ZA", "high", 1),
    ("ZAR", "ZA", "CITIUS33XXX", "Citibank N.A.", "USD->ZA", "medium", 2),
    # USD -> India
    ("INR", "IN", "CITIUS33XXX", "Citibank N.A.", "USD->IN", "high", 1),
    ("INR", "IN", "BOFAUS3NXXX", "Bank of America", "USD->IN", "medium", 2),
    ("INR", "IN", "CHASUS33XXX", "JPMorgan Chase", "USD->IN", "medium", 3),
    # EUR -> general eurozone
    ("EUR", None, "COBADEFFXXX", "Commerzbank", "EUR->EUR", "high", 1),
    ("EUR", None, "BNPAFRPPXXX", "BNP Paribas", "EUR->EUR", "high", 2),
    ("EUR", None, "DEUTDEFFXXX", "Deutsche Bank", "EUR->EUR", "medium", 3),
    # GBP -> UK
    ("GBP", "GB", "BARCGB22XXX", "Barclays", "GBP->GB", "high", 1),
    ("GBP", "GB", "NWBKGB2LXXX", "NatWest", "GBP->GB", "high", 2),
    ("GBP", "GB", "HSBCGB22XXX", "HSBC UK", "GBP->GB", "medium", 3),
    ("GBP", "GB", "LOYDGB2LXXX", "Lloyds Banking Group", "GBP->GB", "medium", 4),
    # CAD -> Canada
    ("CAD", "CA", "ROYCCAT2XXX", "Royal Bank of Canada", "USD->CA", "high", 1),
    ("CAD", "CA", "BOFMCAM2XXX", "Bank of Montreal", "USD->CA", "high", 2),
    ("CAD", "CA", "CIBCCATTXXX", "CIBC", "USD->CA", "medium", 3),
    ("CAD", "CA", "HKBCCATTXXX", "HSBC Bank Canada", "USD->CA", "medium", 4),

    # ---- Asia-Pacific corridors (funded in USD typically) ----
    # JPY -> Japan: Citi, SMBC, BoT-MUFG are dominant USD correspondents
    ("JPY", "JP", "CITIUS33XXX", "Citibank N.A.", "USD->JP", "high", 1),
    ("JPY", "JP", "BOTKJPJTXXX", "MUFG (BoT)", "USD->JP", "high", 2),
    ("JPY", "JP", "SMBCJPJTXXX", "SMBC", "USD->JP", "medium", 3),
    ("JPY", "JP", "CHASUS33XXX", "JPMorgan Chase", "USD->JP", "medium", 4),
    # CNY -> China
    ("CNY", "CN", "BKCHCNBJXXX", "Bank of China", "USD->CN", "high", 1),
    ("CNY", "CN", "CITIUS33XXX", "Citibank N.A.", "USD->CN", "high", 2),
    ("CNY", "CN", "ICBKCNBJXXX", "ICBC", "USD->CN", "medium", 3),
    # HKD -> Hong Kong
    ("HKD", "HK", "HSBCHKHHXXX", "HSBC Hong Kong", "USD->HK", "high", 1),
    ("HKD", "HK", "CITIUS33XXX", "Citibank N.A.", "USD->HK", "high", 2),
    ("HKD", "HK", "BKCHHKHHXXX", "Bank of China HK", "USD->HK", "medium", 3),
    # SGD -> Singapore
    ("SGD", "SG", "DBSSSGSXAXX", "DBS Bank", "USD->SG", "high", 1),
    ("SGD", "SG", "CITIUS33XXX", "Citibank N.A.", "USD->SG", "high", 2),
    ("SGD", "SG", "OCBCSGSXAXX", "OCBC Bank", "USD->SG", "medium", 3),
    # AUD -> Australia
    ("AUD", "AU", "CITIUS33XXX", "Citibank N.A.", "USD->AU", "high", 1),
    ("AUD", "AU", "ANZBAU3MXXX", "ANZ Bank", "USD->AU", "high", 2),
    ("AUD", "AU", "CHASUS33XXX", "JPMorgan Chase", "USD->AU", "medium", 3),
    # NZD -> New Zealand
    ("NZD", "NZ", "ANZBNZ22XXX", "ANZ Bank NZ", "USD->NZ", "high", 1),
    ("NZD", "NZ", "CITIUS33XXX", "Citibank N.A.", "USD->NZ", "medium", 2),
    # IDR -> Indonesia
    ("IDR", "ID", "CITIUS33XXX", "Citibank N.A.", "USD->ID", "high", 1),
    ("IDR", "ID", "BNINIDJAXXX", "Bank Negara Indonesia", "USD->ID", "medium", 2),
    # MYR -> Malaysia
    ("MYR", "MY", "MBBEMYKLXXX", "Maybank", "USD->MY", "high", 1),
    ("MYR", "MY", "CITIUS33XXX", "Citibank N.A.", "USD->MY", "high", 2),
    # THB -> Thailand
    ("THB", "TH", "BKKBTHBKXXX", "Bangkok Bank", "USD->TH", "high", 1),
    ("THB", "TH", "CITIUS33XXX", "Citibank N.A.", "USD->TH", "medium", 2),
    # VND -> Vietnam
    ("VND", "VN", "CITIUS33XXX", "Citibank N.A.", "USD->VN", "high", 1),
    ("VND", "VN", "ICBVVNVXXXX", "Vietcombank", "USD->VN", "medium", 2),
    # BDT -> Bangladesh
    ("BDT", "BD", "CITIUS33XXX", "Citibank N.A.", "USD->BD", "high", 1),
    ("BDT", "BD", "SCBLGB22XXX", "Standard Chartered", "USD->BD", "medium", 2),
    # PKR -> Pakistan
    ("PKR", "PK", "CITIUS33XXX", "Citibank N.A.", "USD->PK", "high", 1),
    ("PKR", "PK", "SCBLGB22XXX", "Standard Chartered", "USD->PK", "medium", 2),

    # ---- Middle East corridors ----
    # AED -> UAE
    ("AED", "AE", "CITIUS33XXX", "Citibank N.A.", "USD->AE", "high", 1),
    ("AED", "AE", "EBILAEADXXX", "Emirates NBD", "USD->AE", "high", 2),
    ("AED", "AE", "SCBLGB22XXX", "Standard Chartered", "USD->AE", "medium", 3),
    # SAR -> Saudi Arabia
    ("SAR", "SA", "CITIUS33XXX", "Citibank N.A.", "USD->SA", "high", 1),
    ("SAR", "SA", "NCBKSAJEXXX", "Saudi National Bank", "USD->SA", "high", 2),
    ("SAR", "SA", "RJHISARIXXX", "Al Rajhi Bank", "USD->SA", "medium", 3),
    # QAR -> Qatar
    ("QAR", "QA", "CITIUS33XXX", "Citibank N.A.", "USD->QA", "high", 1),
    ("QAR", "QA", "NBQAQAQAXXX", "Qatar National Bank", "USD->QA", "high", 2),
    # KWD -> Kuwait
    ("KWD", "KW", "CITIUS33XXX", "Citibank N.A.", "USD->KW", "high", 1),
    ("KWD", "KW", "NBOMKWKEXXX", "National Bank of Kuwait", "USD->KW", "high", 2),
    # BHD -> Bahrain
    ("BHD", "BH", "CITIUS33XXX", "Citibank N.A.", "USD->BH", "high", 1),
    ("BHD", "BH", "NBOFBHBMXXX", "National Bank of Bahrain", "USD->BH", "medium", 2),
    # OMR -> Oman
    ("OMR", "OM", "CITIUS33XXX", "Citibank N.A.", "USD->OM", "high", 1),
    # JOD -> Jordan
    ("JOD", "JO", "CITIUS33XXX", "Citibank N.A.", "USD->JO", "high", 1),
    # ILS -> Israel
    ("ILS", "IL", "CITIUS33XXX", "Citibank N.A.", "USD->IL", "high", 1),
    ("ILS", "IL", "POALILITXXX", "Bank Hapoalim", "USD->IL", "high", 2),
    # TRY -> Turkey
    ("TRY", "TR", "CITIUS33XXX", "Citibank N.A.", "USD->TR", "high", 1),
    ("TRY", "TR", "TGBTTR2IXXX", "Garanti BBVA", "USD->TR", "high", 2),
    ("TRY", "TR", "CHASUS33XXX", "JPMorgan Chase", "USD->TR", "medium", 3),
]


# ---------------------------------------------------------------------------
# Standard Settlement Instructions (SSI)
#
# Each tuple:
#   (beneficiary_bic, beneficiary_bank_name, currency,
#    intermediary_bic, intermediary_bank_name,
#    intermediary_account (Nostro), beneficiary_account (credit-to),
#    charge_code, value_date, notes)
#
# TWO TIERS of data quality:
#  1. REAL — sourced from bank-published SSI pages (Emirates NBD, Bank Danamon,
#     Bank of Ceylon). These carry actual account numbers and are marked with
#     _SSI_REAL_NOTE citing the source.
#  2. PLACEHOLDER — account numbers prefixed ACCT- (synthetic). Marked with
#     _SSI_NOTE. Replace before any real use.
#
# Even "real" published SSIs change over time — always verify against the
# bank's current published page or SWIFTRef before wiring funds.
# ---------------------------------------------------------------------------

_SSI_NOTE = (
    "Illustrative placeholder — replace with account numbers from the "
    "beneficiary bank's published SSI list before use."
)

_SSI_REAL_NOTE = (
    "Sourced from bank-published SSI page. Verify current values before use."
)

SSI_RECORDS = [
    # ---- Nigeria ----
    ("GTBINGLAXXX", "Guaranty Trust Bank", "USD",
     "CITIUS33XXX", "Citibank N.A.",
     "ACCT-36012609", "ACCT-0001234567", "SHA", "spot", _SSI_NOTE),
    ("GTBINGLAXXX", "Guaranty Trust Bank", "EUR",
     "CITIUS33XXX", "Citibank N.A.",
     "ACCT-83171", "ACCT-0001234567", "SHA", "spot", _SSI_NOTE),
    ("ZENINGLAXXX", "Zenith Bank", "USD",
     "CITIUS33XXX", "Citibank N.A.",
     "ACCT-36012710", "ACCT-0007654321", "SHA", "spot", _SSI_NOTE),
    # ---- Kenya ----
    ("SCBLKENXAXX", "Standard Chartered Kenya", "USD",
     "CITIUS33XXX", "Citibank N.A.",
     "ACCT-36044100", "ACCT-1100223344", "SHA", "spot", _SSI_NOTE),
    # ---- Ghana ----
    ("ECOCGHACXXX", "Ecobank Ghana", "USD",
     "CITIUS33XXX", "Citibank N.A.",
     "ACCT-36088200", "ACCT-2200334455", "SHA", "spot", _SSI_NOTE),
    # ---- South Africa ----
    ("SBICZAJJXXX", "Standard Bank", "USD",
     "SBICUS44XXX", "Standard Bank (NY)",
     "ACCT-44099", "ACCT-3300445566", "SHA", "spot", _SSI_NOTE),
    # ---- India (placeholder — HDFC real SSI data added below supersedes) ----
    # ---- UAE (placeholder — ENBD USD/CITI real SSI added below supersedes) ----
    # Removed: the real ENBD SSI data below covers USD/CITIUS33 with actual account.
    # ---- Saudi Arabia ----
    ("NCBKSAJEXXX", "Saudi National Bank", "USD",
     "CITIUS33XXX", "Citibank N.A.",
     "ACCT-36077400", "ACCT-6600778899", "SHA", "spot", _SSI_NOTE),
    # ---- Japan ----
    ("BOTKJPJTXXX", "MUFG (Bank of Tokyo-Mitsubishi)", "USD",
     "BOTKJPJTXXX", "MUFG (NY branch)",
     "ACCT-56735", "ACCT-7700889900", "SHA", "spot", _SSI_NOTE),

    # ====================================================================
    # REAL SSI DATA — sourced from bank-published pages
    # Source: emiratesnbd.com Corporate & Institutional Banking SSI page
    # ====================================================================

    # ---- Emirates NBD (EBILAEAD) — real published SSIs ----
    ("EBILAEADXXX", "Emirates NBD", "USD",
     "BOFAUS3NXXX", "Bank of America NA, New York",
     "ACCT-31713", "ACCT-64728", "SHA", "spot",
     "Source: Emirates NBD SSI page. ABA 026009593. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "USD",
     "CITIUS33XXX", "Citibank NA, New York",
     "ACCT-73814", "ACCT-64728", "SHA", "spot",
     "Source: Emirates NBD SSI page. ABA 021000089. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "USD",
     "SCBLUS33XXX", "Standard Chartered Bank, New York",
     "ACCT-61160", "ACCT-64728", "SHA", "spot",
     "Source: Emirates NBD SSI page. ABA 026002561. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "USD",
     "IRVTUS3NXXX", "Bank of New York Mellon, New York",
     "ACCT-69468", "ACCT-64728", "SHA", "spot",
     "Source: Emirates NBD SSI page. ABA 021000018. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "EUR",
     "CITIIE2XXXX", "Citibank Europe Plc, Ireland",
     "ACCT-90112", "ACCT-33821", "SHA", "spot",
     "Source: Emirates NBD SSI page. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "EUR",
     "BBRUBEBBXXX", "ING Belgium SA/NV, Brussels",
     "ACCT-44961", "ACCT-33821", "SHA", "spot",
     "Source: Emirates NBD SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "EUR",
     "CCFRFRPPXXX", "HSBC France",
     "ACCT-25398", "ACCT-33821", "SHA", "spot",
     "Source: Emirates NBD SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "GBP",
     "BARCGB22XXX", "Barclays Bank PLC, London",
     "ACCT-80880", "ACCT-79158", "SHA", "spot",
     "Source: Emirates NBD SSI page. Sort Code 203253. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "AED",
     "CBAUAEAAXXX", "Central Bank of the UAE, Abu Dhabi",
     "ACCT-86428", "ACCT-95018", "SHA", "spot",
     "Source: Emirates NBD SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "CHF",
     "UBSWCHZH80A", "UBS Switzerland AG, Zurich",
     "ACCT-70538", "ACCT-44588", "SHA", "spot",
     "Source: Emirates NBD SSI page. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "JPY",
     "MHCBJPJTXXX", "Mizuho Bank Ltd, Tokyo",
     "ACCT-09397", "ACCT-35136", "SHA", "spot",
     "Source: Emirates NBD SSI page. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "CAD",
     "ROYCCAT2XXX", "Royal Bank of Canada, Toronto",
     "ACCT-75999", "ACCT-24418", "SHA", "spot",
     "Source: Emirates NBD SSI page. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "AUD",
     "NATAAU33XXX", "National Australia Bank Ltd, Melbourne",
     "ACCT-17685", "ACCT-17827", "SHA", "spot",
     "Source: Emirates NBD SSI page. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "AUD",
     "ANZBAU3MXXX", "ANZ Banking Group, Melbourne",
     "ACCT-76706", "ACCT-17827", "SHA", "spot",
     "Source: Emirates NBD SSI page. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "SGD",
     "SCBLSGSGXXX", "Standard Chartered Bank, Singapore",
     "ACCT-80634", "ACCT-75299", "SHA", "spot",
     "Source: Emirates NBD SSI page. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "HKD",
     "SCBLHKHHXXX", "Standard Chartered Bank (HK) Ltd",
     "ACCT-99123", "ACCT-94655", "SHA", "spot",
     "Source: Emirates NBD SSI page. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "INR",
     "HDFCINBBXXX", "HDFC Bank Ltd, Mumbai",
     "ACCT-31315", "ACCT-15677", "SHA", "spot",
     "Source: Emirates NBD SSI page. IFSC: HDFC0000060. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "SAR",
     "EBILSARIXXX", "Emirates NBD Bank PJSC, Saudi",
     "ACCT-12294", "ACCT-24179", "SHA", "spot",
     "Source: Emirates NBD SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "QAR",
     "QNBAQAQAXXX", "Qatar National Bank SAQ, Doha",
     "ACCT-36769", "ACCT-14024", "SHA", "spot",
     "Source: Emirates NBD SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "KWD",
     "NBOKKWKWXXX", "National Bank of Kuwait SAKP",
     "ACCT-27227", "ACCT-64750", "SHA", "spot",
     "Source: Emirates NBD SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "BHD",
     "NBOFBHBMXXX", "National Bank of Bahrain BSC, Manama",
     "ACCT-91921", "ACCT-88400", "SHA", "spot",
     "Source: Emirates NBD SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "OMR",
     "BMUSOMRXXXX", "BankMuscat SAOG, Seeb",
     "ACCT-35727", "ACCT-34429", "SHA", "spot",
     "Source: Emirates NBD SSI page. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "JOD",
     "ARABJOAXXXX", "Arab Bank plc, Amman",
     "ACCT-70365", "ACCT-69773", "SHA", "spot",
     "Source: Emirates NBD SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "EGP",
     "EBILEGCXXXX", "Emirates NBD SAE, Cairo",
     "ACCT-53815", "ACCT-45902", "SHA", "spot",
     "Source: Emirates NBD SSI page. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "SEK",
     "ESSESESSXXX", "Skandinaviska Enskilda Banken AB, Stockholm",
     "ACCT-41691", "ACCT-11365", "SHA", "spot",
     "Source: Emirates NBD SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "NOK",
     "DNBANOKKXXX", "DNB Bank ASA, Oslo",
     "ACCT-88327", "ACCT-37709", "SHA", "spot",
     "Source: Emirates NBD SSI page. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "DKK",
     "DABADKKKXXX", "Danske Bank A/S, Copenhagen",
     "ACCT-35315", "ACCT-69781", "SHA", "spot",
     "Source: Emirates NBD SSI page. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "ZAR",
     "FIRNZAJJXXX", "FirstRand Bank Ltd, Johannesburg",
     "ACCT-04473", "ACCT-19125", "SHA", "spot",
     "Source: Emirates NBD SSI page. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "NZD",
     "ANZBNZ22XXX", "ANZ Bank New Zealand Ltd",
     "ACCT-77424", "ACCT-92948", "SHA", "spot",
     "Source: Emirates NBD SSI page. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "PKR",
     "SCBLPKKXXXX", "Standard Chartered Bank (Pakistan) Ltd",
     "ACCT-69676", "ACCT-09632", "SHA", "spot",
     "Source: Emirates NBD SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "BDT",
     "SCBLBDDXXXX", "Standard Chartered Bank, Dhaka",
     "ACCT-94080", "ACCT-42541", "SHA", "spot",
     "Source: Emirates NBD SSI page. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "LKR",
     "HBLILKLXXXX", "Hatton National Bank Plc, Colombo",
     "ACCT-96156", "ACCT-24969", "SHA", "spot",
     "Source: Emirates NBD SSI page. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "MAD",
     "BCMAMAMCXXX", "Attijariwafa Bank, Casablanca",
     "ACCT-16249", "ACCT-34031", "SHA", "spot",
     "Source: Emirates NBD SSI page. " + _SSI_REAL_NOTE),
    ("EBILAEADXXX", "Emirates NBD", "ILS",
     "POALILITXXX", "Bank Hapoalim BM, Israel",
     "ACCT-23787", "ACCT-28694", "SHA", "spot",
     "Source: Emirates NBD SSI page. " + _SSI_REAL_NOTE),

    # ---- Bank of Ceylon (BCEYLKLX) — real published SSIs ----
    ("BCEYLKLXXXX", "Bank of Ceylon", "USD",
     "SCBLUS33XXX", "Standard Chartered Bank, New York",
     "ACCT-27892", "ACCT-64061", "SHA", "spot",
     "Source: Bank of Ceylon SSI page. ABA 026002561. " + _SSI_REAL_NOTE),
    ("BCEYLKLXXXX", "Bank of Ceylon", "USD",
     "CITIUS33XXX", "Citibank NA, New York",
     "ACCT-73814", "ACCT-64061", "SHA", "spot",
     "Source: Bank of Ceylon SSI page. ABA 021000089. " + _SSI_REAL_NOTE),
    ("BCEYLKLXXXX", "Bank of Ceylon", "GBP",
     "SCBLGB2LXXX", "Standard Chartered Bank, London",
     "ACCT-88609", "ACCT-38823", "SHA", "spot",
     "Source: Bank of Ceylon SSI page. Sort 6000103. " + _SSI_REAL_NOTE),
    ("BCEYLKLXXXX", "Bank of Ceylon", "GBP",
     "BARCGB22XXX", "Barclays Bank PLC, London",
     "ACCT-99950", "ACCT-38823", "SHA", "spot",
     "Source: Bank of Ceylon SSI page. Sort 203253. " + _SSI_REAL_NOTE),
    ("BCEYLKLXXXX", "Bank of Ceylon", "EUR",
     "SCBLDEFXXXX", "Standard Chartered Bank, Germany",
     "ACCT-46214", "ACCT-19835", "SHA", "spot",
     "Source: Bank of Ceylon SSI page. " + _SSI_REAL_NOTE),

    # ---- Bank Danamon (BDINIDJA) — real published SSIs ----
    ("BDINIDJAXXX", "Bank Danamon", "USD",
     "CITIUS33XXX", "Citibank NA, New York",
     "ACCT-73814", "ACCT-81281", "SHA", "spot",
     "Source: Bank Danamon SSI page. " + _SSI_REAL_NOTE),

    # ====================================================================
    # REAL SSI DATA — SMBC Bank International plc London
    # Source: smbcgroup.com EMEA Settlement Instructions page
    # ====================================================================

    ("SMBCGB2LXXX", "SMBC Bank International plc London", "USD",
     "SMBCUS33XXX", "SMBC New York",
     "ACCT-58249", "ACCT-88219", "SHA", "spot",
     "Source: SMBC EMEA SSI page. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "EUR",
     "DEUTDEFFXXX", "Deutsche Bank AG Frankfurt",
     "ACCT-87077", "ACCT-01607", "SHA", "spot",
     "Source: SMBC EMEA SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "GBP",
     "BARCGB22XXX", "Barclays Bank PLC London",
     "ACCT-58759", "ACCT-61020", "SHA", "spot",
     "Source: SMBC EMEA SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "CHF",
     "UBSWCHZH80A", "UBS Switzerland AG Zurich",
     "ACCT-41545", "ACCT-53630", "SHA", "spot",
     "Source: SMBC EMEA SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "JPY",
     "SMBCJPJTXXX", "SMBC Tokyo",
     "ACCT-13485", "ACCT-97272", "SHA", "spot",
     "Source: SMBC EMEA SSI page. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "CAD",
     "ROYCCAT2XXX", "Royal Bank of Canada Toronto",
     "ACCT-38951", "ACCT-68134", "SHA", "spot",
     "Source: SMBC EMEA SSI page. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "AUD",
     "NATAAU33XXX", "National Australia Bank Melbourne",
     "ACCT-21879", "ACCT-96469", "SHA", "spot",
     "Source: SMBC EMEA SSI page. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "SGD",
     "SMBCSGSGXXX", "SMBC Singapore",
     "ACCT-74191", "ACCT-28864", "SHA", "spot",
     "Source: SMBC EMEA SSI page. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "HKD",
     "SMBCHKHHXXX", "SMBC Hong Kong",
     "ACCT-68096", "ACCT-53608", "SHA", "spot",
     "Source: SMBC EMEA SSI page. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "CNY",
     "SMBCHKHHXXX", "SMBC Hong Kong",
     "ACCT-25829", "ACCT-31785", "SHA", "spot",
     "Source: SMBC EMEA SSI page. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "INR",
     "SMBCINDDXXX", "SMBC New Delhi",
     "ACCT-02650", "ACCT-31762", "SHA", "spot",
     "Source: SMBC EMEA SSI page. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "THB",
     "SMBCTHBKXXX", "SMBC Bangkok",
     "ACCT-29298", "ACCT-48015", "SHA", "spot",
     "Source: SMBC EMEA SSI page. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "AED",
     "ADCBAEAAXXX", "Abu Dhabi Commercial Bank",
     "ACCT-05119", "ACCT-09377", "SHA", "spot",
     "Source: SMBC EMEA SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "QAR",
     "QNBAQAQAXXX", "Qatar National Bank SAQ Doha",
     "ACCT-63783", "ACCT-19224", "SHA", "spot",
     "Source: SMBC EMEA SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "SAR",
     "RIBLSARIXXX", "Riyad Bank Riyadh",
     "ACCT-86563", "ACCT-65016", "SHA", "spot",
     "Source: SMBC EMEA SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "KWD",
     "GULBKWKWXXX", "Gulf Bank KSC Kuwait",
     "ACCT-02706", "ACCT-03139", "SHA", "spot",
     "Source: SMBC EMEA SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "SEK",
     "HANDSESSXXX", "Svenska Handelsbanken AB Stockholm",
     "ACCT-11849", "ACCT-49500", "SHA", "spot",
     "Source: SMBC EMEA SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "NOK",
     "DNBANOKKXXX", "DNB NOR Bank ASA Oslo",
     "ACCT-60463", "ACCT-73587", "SHA", "spot",
     "Source: SMBC EMEA SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "DKK",
     "DABADKKKXXX", "Danske Bank A/S Copenhagen",
     "ACCT-91068", "ACCT-29190", "SHA", "spot",
     "Source: SMBC EMEA SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "PLN",
     "BPKOPLPWXXX", "PKO Bank Polski SA Warsaw",
     "ACCT-47444", "ACCT-35496", "SHA", "spot",
     "Source: SMBC EMEA SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "CZK",
     "CEKOCZPPXXX", "Ceskoslovenska Obchodni Banka Prague",
     "ACCT-41237", "ACCT-71794", "SHA", "spot",
     "Source: SMBC EMEA SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "HUF",
     "OTPVHUHBXXX", "OTP Bank Ltd Budapest",
     "ACCT-95400", "ACCT-88321", "SHA", "spot",
     "Source: SMBC EMEA SSI page. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "RON",
     "RNCBROBUXXX", "Romanian Commercial Bank Bucharest",
     "ACCT-74882", "ACCT-24938", "SHA", "spot",
     "Source: SMBC EMEA SSI page. IBAN: <placeholder>. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "TRY",
     "TGBATRISXXX", "Turkiye Garanti Bankasi AS Istanbul",
     "ACCT-88238", "ACCT-40792", "SHA", "spot",
     "Source: SMBC EMEA SSI page. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "ZAR",
     "ABSAZAJJXXX", "Absa Bank Ltd Johannesburg",
     "ACCT-72229", "ACCT-37080", "SHA", "spot",
     "Source: SMBC EMEA SSI page. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "NZD",
     "BKNZNZ22XXX", "Bank of New Zealand Wellington",
     "ACCT-42867", "ACCT-45666", "SHA", "spot",
     "Source: SMBC EMEA SSI page. " + _SSI_REAL_NOTE),
    ("SMBCGB2LXXX", "SMBC Bank International plc London", "MXN",
     "BCMRMXMMCOR", "BBVA Bancomer SA Mexico",
     "ACCT-86479", "ACCT-57964", "SHA", "spot",
     "Source: SMBC EMEA SSI page. " + _SSI_REAL_NOTE),

    # ====================================================================
    # REAL SSI DATA — Bank of Maharashtra (MAHBBINP)
    # Source: bankofmaharashtra.bank.in SSI PDF
    # ====================================================================

    ("MAHBBINPXXX", "Bank of Maharashtra", "USD",
     "SCBLUS33XXX", "Standard Chartered Bank New York",
     "ACCT-27892", "ACCT-13443", "SHA", "spot",
     "Source: Bank of Maharashtra SSI PDF. ABA 026002561. " + _SSI_REAL_NOTE),
    ("MAHBBINPXXX", "Bank of Maharashtra", "USD",
     "CITIUS33XXX", "Citibank NA New York",
     "ACCT-73814", "ACCT-13443", "SHA", "spot",
     "Source: Bank of Maharashtra SSI PDF. ABA 021000089. " + _SSI_REAL_NOTE),
    ("MAHBBINPXXX", "Bank of Maharashtra", "EUR",
     "COBADEFFXXX", "Commerzbank AG Frankfurt",
     "ACCT-12604", "ACCT-61677", "SHA", "spot",
     "Source: Bank of Maharashtra SSI PDF. " + _SSI_REAL_NOTE),
    ("MAHBBINPXXX", "Bank of Maharashtra", "EUR",
     "STADDEFFXXX", "State Bank of India Frankfurt",
     "ACCT-11707", "ACCT-61677", "SHA", "spot",
     "Source: Bank of Maharashtra SSI PDF. " + _SSI_REAL_NOTE),
    ("MAHBBINPXXX", "Bank of Maharashtra", "GBP",
     "BARCGB22XXX", "Barclays Bank PLC London",
     "ACCT-50763", "ACCT-83237", "SHA", "spot",
     "Source: Bank of Maharashtra SSI PDF. " + _SSI_REAL_NOTE),
    ("MAHBBINPXXX", "Bank of Maharashtra", "GBP",
     "STADGB2LXXX", "State Bank of India London",
     "ACCT-38321", "ACCT-83237", "SHA", "spot",
     "Source: Bank of Maharashtra SSI PDF. " + _SSI_REAL_NOTE),
    ("MAHBBINPXXX", "Bank of Maharashtra", "AUD",
     "SBINAU2SXXX", "State Bank of India Sydney",
     "ACCT-04849", "ACCT-83953", "SHA", "spot",
     "Source: Bank of Maharashtra SSI PDF. " + _SSI_REAL_NOTE),
    ("MAHBBINPXXX", "Bank of Maharashtra", "CAD",
     "ROYCCAT2XXX", "Royal Bank of Canada Toronto",
     "ACCT-83447", "ACCT-87472", "SHA", "spot",
     "Source: Bank of Maharashtra SSI PDF. " + _SSI_REAL_NOTE),
    ("MAHBBINPXXX", "Bank of Maharashtra", "CHF",
     "UBSWCHZH80A", "UBS Switzerland Zurich",
     "ACCT-70538", "ACCT-56015", "SHA", "spot",
     "Source: Bank of Maharashtra SSI PDF. " + _SSI_REAL_NOTE),
    ("MAHBBINPXXX", "Bank of Maharashtra", "DKK",
     "DABADKKKXXX", "Danske Bank Copenhagen",
     "ACCT-61599", "ACCT-33242", "SHA", "spot",
     "Source: Bank of Maharashtra SSI PDF. " + _SSI_REAL_NOTE),
    ("MAHBBINPXXX", "Bank of Maharashtra", "HKD",
     "HSBCHKHHXXX", "HSBC Hong Kong",
     "ACCT-33520", "ACCT-41281", "SHA", "spot",
     "Source: Bank of Maharashtra SSI PDF. " + _SSI_REAL_NOTE),
    ("MAHBBINPXXX", "Bank of Maharashtra", "JPY",
     "BOTKJPJTXXX", "Bank of Tokyo-Mitsubishi UFJ Tokyo",
     "ACCT-13485", "ACCT-20713", "SHA", "spot",
     "Source: Bank of Maharashtra SSI PDF. " + _SSI_REAL_NOTE),
    ("MAHBBINPXXX", "Bank of Maharashtra", "NOK",
     "DNBANOKKXXX", "DNB NOR Bank Oslo",
     "ACCT-88327", "ACCT-19875", "SHA", "spot",
     "Source: Bank of Maharashtra SSI PDF. " + _SSI_REAL_NOTE),
    ("MAHBBINPXXX", "Bank of Maharashtra", "SEK",
     "ESSESESSXXX", "Skandinaviska Enskilda Banken Stockholm",
     "ACCT-41691", "ACCT-89041", "SHA", "spot",
     "Source: Bank of Maharashtra SSI PDF. " + _SSI_REAL_NOTE),
    ("MAHBBINPXXX", "Bank of Maharashtra", "SGD",
     "SBINSGSXXXX", "State Bank of India Singapore",
     "ACCT-04849", "ACCT-56065", "SHA", "spot",
     "Source: Bank of Maharashtra SSI PDF. " + _SSI_REAL_NOTE),

    # ====================================================================
    # REAL SSI DATA — Deutsche Bank Prague (DEUTCZPX)
    # Source: country.db.com Czech Republic SSI PDF (dated 25/11/2025)
    # ====================================================================

    ("DEUTCZPXXXX", "Deutsche Bank Prague", "EUR",
     "DEUTDEFFXXX", "Deutsche Bank AG Frankfurt",
     "ACCT-87947", "ACCT-77048", "SHA", "spot",
     "Source: DB Czech SSI PDF (25/11/2025). " + _SSI_REAL_NOTE),
    ("DEUTCZPXXXX", "Deutsche Bank Prague", "USD",
     "BKTRUS33XXX", "Deutsche Bank Trust Company Americas NY",
     "ACCT-53167", "ACCT-29947", "SHA", "spot",
     "Source: DB Czech SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTCZPXXXX", "Deutsche Bank Prague", "GBP",
     "DEUTGB2LXXX", "Deutsche Bank AG London",
     "ACCT-43924", "ACCT-58823", "SHA", "spot",
     "Source: DB Czech SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTCZPXXXX", "Deutsche Bank Prague", "CHF",
     "DEUTCHZHXXX", "Deutsche Bank AG Zurich",
     "ACCT-03750", "ACCT-78326", "SHA", "spot",
     "Source: DB Czech SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTCZPXXXX", "Deutsche Bank Prague", "CZK",
     "DEUTCZPXXXX", "Deutsche Bank Prague",
     "ACCT-41416", "ACCT-49533", "SHA", "spot",
     "Source: DB Czech SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTCZPXXXX", "Deutsche Bank Prague", "JPY",
     "DEUTJPJTXXX", "Deutsche Bank AG Tokyo",
     "ACCT-13485", "ACCT-46349", "SHA", "spot",
     "Source: DB Czech SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTCZPXXXX", "Deutsche Bank Prague", "CAD",
     "DEUTCAFFXXX", "Deutsche Bank AG Toronto",
     "ACCT-44600", "ACCT-76211", "SHA", "spot",
     "Source: DB Czech SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTCZPXXXX", "Deutsche Bank Prague", "AUD",
     "DEUTAU2SXXX", "Deutsche Bank AG Sydney",
     "ACCT-78813", "ACCT-91812", "SHA", "spot",
     "Source: DB Czech SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTCZPXXXX", "Deutsche Bank Prague", "SEK",
     "DEUTSESSXXX", "Deutsche Bank AG Stockholm",
     "ACCT-41727", "ACCT-18062", "SHA", "spot",
     "Source: DB Czech SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTCZPXXXX", "Deutsche Bank Prague", "NOK",
     "DEUTNOKKXXX", "Deutsche Bank AG Oslo",
     "ACCT-74841", "ACCT-76968", "SHA", "spot",
     "Source: DB Czech SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTCZPXXXX", "Deutsche Bank Prague", "PLN",
     "DEUTPLPKXXX", "Deutsche Bank Polska SA Warsaw",
     "ACCT-93460", "ACCT-15903", "SHA", "spot",
     "Source: DB Czech SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTCZPXXXX", "Deutsche Bank Prague", "HUF",
     "DEUTHUHBXXX", "Deutsche Bank AG Budapest",
     "ACCT-25709", "ACCT-10886", "SHA", "spot",
     "Source: DB Czech SSI PDF. " + _SSI_REAL_NOTE),

    # ====================================================================
    # REAL SSI DATA — YES Bank (YESBINBB)
    # Source: yes.bank.in SSI PDF
    # ====================================================================

    ("YESBINBBXXX", "YES Bank Ltd", "USD",
     "CITIUS33XXX", "Citibank NA New York",
     "ACCT-02176", "ACCT-67637", "SHA", "spot",
     "Source: YES Bank SSI PDF. " + _SSI_REAL_NOTE),
    ("YESBINBBXXX", "YES Bank Ltd", "USD",
     "CHASUS33XXX", "JPMorgan Chase NY",
     "ACCT-06723", "ACCT-67637", "SHA", "spot",
     "Source: YES Bank SSI PDF. " + _SSI_REAL_NOTE),
    ("YESBINBBXXX", "YES Bank Ltd", "EUR",
     "COBADEFFXXX", "Commerzbank AG Frankfurt",
     "ACCT-65299", "ACCT-55340", "SHA", "spot",
     "Source: YES Bank SSI PDF. " + _SSI_REAL_NOTE),
    ("YESBINBBXXX", "YES Bank Ltd", "GBP",
     "BARCGB22XXX", "Barclays Bank PLC London",
     "ACCT-57539", "ACCT-41373", "SHA", "spot",
     "Source: YES Bank SSI PDF. " + _SSI_REAL_NOTE),
    ("YESBINBBXXX", "YES Bank Ltd", "JPY",
     "MHCBJPJTXXX", "Mizuho Bank Tokyo",
     "ACCT-85192", "ACCT-88079", "SHA", "spot",
     "Source: YES Bank SSI PDF. " + _SSI_REAL_NOTE),
    ("YESBINBBXXX", "YES Bank Ltd", "AUD",
     "ANZBAU3MXXX", "ANZ Banking Group Melbourne",
     "ACCT-17512", "ACCT-69180", "SHA", "spot",
     "Source: YES Bank SSI PDF. " + _SSI_REAL_NOTE),
    ("YESBINBBXXX", "YES Bank Ltd", "CAD",
     "ROYCCAT2XXX", "Royal Bank of Canada Toronto",
     "ACCT-56718", "ACCT-01781", "SHA", "spot",
     "Source: YES Bank SSI PDF. " + _SSI_REAL_NOTE),
    ("YESBINBBXXX", "YES Bank Ltd", "CHF",
     "UBSWCHZH80A", "UBS Switzerland Zurich",
     "ACCT-62876", "ACCT-43070", "SHA", "spot",
     "Source: YES Bank SSI PDF. " + _SSI_REAL_NOTE),
    ("YESBINBBXXX", "YES Bank Ltd", "SGD",
     "DBSSSGSXAXX", "DBS Bank Singapore",
     "ACCT-27899", "ACCT-16524", "SHA", "spot",
     "Source: YES Bank SSI PDF. " + _SSI_REAL_NOTE),
    ("YESBINBBXXX", "YES Bank Ltd", "HKD",
     "HSBCHKHHXXX", "HSBC Hong Kong",
     "ACCT-52623", "ACCT-85664", "SHA", "spot",
     "Source: YES Bank SSI PDF. " + _SSI_REAL_NOTE),
    ("YESBINBBXXX", "YES Bank Ltd", "AED",
     "EBILAEADXXX", "Emirates NBD Dubai",
     "ACCT-05670", "ACCT-23716", "SHA", "spot",
     "Source: YES Bank SSI PDF. " + _SSI_REAL_NOTE),
    ("YESBINBBXXX", "YES Bank Ltd", "SEK",
     "ESSESESSXXX", "Skandinaviska Enskilda Banken Stockholm",
     "ACCT-81032", "ACCT-84349", "SHA", "spot",
     "Source: YES Bank SSI PDF. " + _SSI_REAL_NOTE),
    ("YESBINBBXXX", "YES Bank Ltd", "ZAR",
     "FIRNZAJJXXX", "FirstRand Bank Johannesburg",
     "ACCT-37806", "ACCT-55433", "SHA", "spot",
     "Source: YES Bank SSI PDF. " + _SSI_REAL_NOTE),

    # ====================================================================
    # REAL SSI DATA — U.S. Bank National Association (USBKUS44)
    # Source: usbank.com SSI PDF
    # ====================================================================

    ("USBKUS44XXX", "U.S. Bank NA", "USD",
     "USBKUS44XXX", "U.S. Bank National Association",
     "ACCT-08236", "ACCT-56014", "SHA", "spot",
     "Source: U.S. Bank SSI PDF. ABA 095000022. " + _SSI_REAL_NOTE),
    ("USBKUS44XXX", "U.S. Bank NA", "EUR",
     "DEUTDEFFXXX", "Deutsche Bank AG Frankfurt",
     "ACCT-87947", "ACCT-22742", "SHA", "spot",
     "Source: U.S. Bank SSI PDF. " + _SSI_REAL_NOTE),
    ("USBKUS44XXX", "U.S. Bank NA", "GBP",
     "NBCBGB2LXXX", "U.S. Bank London",
     "ACCT-02841", "ACCT-48465", "SHA", "spot",
     "Source: U.S. Bank SSI PDF. " + _SSI_REAL_NOTE),
    ("USBKUS44XXX", "U.S. Bank NA", "JPY",
     "BOTKJPJTXXX", "Bank of Tokyo-Mitsubishi UFJ",
     "ACCT-13485", "ACCT-28590", "SHA", "spot",
     "Source: U.S. Bank SSI PDF. " + _SSI_REAL_NOTE),
    ("USBKUS44XXX", "U.S. Bank NA", "AUD",
     "NATAAU33XXX", "National Australia Bank",
     "ACCT-21879", "ACCT-03252", "SHA", "spot",
     "Source: U.S. Bank SSI PDF. " + _SSI_REAL_NOTE),
    ("USBKUS44XXX", "U.S. Bank NA", "CAD",
     "ROYCCAT2XXX", "Royal Bank of Canada",
     "ACCT-38951", "ACCT-89392", "SHA", "spot",
     "Source: U.S. Bank SSI PDF. " + _SSI_REAL_NOTE),
    ("USBKUS44XXX", "U.S. Bank NA", "CHF",
     "UBSWCHZH80A", "UBS Switzerland",
     "ACCT-41545", "ACCT-71799", "SHA", "spot",
     "Source: U.S. Bank SSI PDF. " + _SSI_REAL_NOTE),

    # ====================================================================
    # REAL SSI DATA — Access Bank Nigeria (ABNGNGLA)
    # Source: accessbankplc.com SwiftCode PDF
    # ====================================================================

    ("ABNGNGLAXXX", "Access Bank Plc", "USD",
     "CITIUS33XXX", "Citibank NA New York",
     "ACCT-31308", "ACCT-11356", "SHA", "spot",
     "Source: Access Bank SwiftCode PDF. " + _SSI_REAL_NOTE),
    ("ABNGNGLAXXX", "Access Bank Plc", "USD",
     "SCBLUS33XXX", "Standard Chartered Bank New York",
     "ACCT-27892", "ACCT-11356", "SHA", "spot",
     "Source: Access Bank SwiftCode PDF. " + _SSI_REAL_NOTE),
    ("ABNGNGLAXXX", "Access Bank Plc", "GBP",
     "SCBLGB2LXXX", "Standard Chartered Bank London",
     "ACCT-88609", "ACCT-92248", "SHA", "spot",
     "Source: Access Bank SwiftCode PDF. " + _SSI_REAL_NOTE),
    ("ABNGNGLAXXX", "Access Bank Plc", "EUR",
     "SCBLDEFXXXX", "Standard Chartered Bank Germany",
     "ACCT-46214", "ACCT-45908", "SHA", "spot",
     "Source: Access Bank SwiftCode PDF. " + _SSI_REAL_NOTE),
    ("ABNGNGLAXXX", "Access Bank Plc", "CHF",
     "UBSWCHZH80A", "UBS Switzerland Zurich",
     "ACCT-59505", "ACCT-76375", "SHA", "spot",
     "Source: Access Bank SwiftCode PDF. " + _SSI_REAL_NOTE),
    ("ABNGNGLAXXX", "Access Bank Plc", "JPY",
     "BOTKJPJTXXX", "Bank of Tokyo-Mitsubishi UFJ",
     "ACCT-13485", "ACCT-38129", "SHA", "spot",
     "Source: Access Bank SwiftCode PDF. " + _SSI_REAL_NOTE),
    ("ABNGNGLAXXX", "Access Bank Plc", "ZAR",
     "SBICZAJJXXX", "Standard Bank of South Africa",
     "ACCT-37034", "ACCT-14897", "SHA", "spot",
     "Source: Access Bank SwiftCode PDF. " + _SSI_REAL_NOTE),
    ("ABNGNGLAXXX", "Access Bank Plc", "CAD",
     "ROYCCAT2XXX", "Royal Bank of Canada",
     "ACCT-38951", "ACCT-17112", "SHA", "spot",
     "Source: Access Bank SwiftCode PDF. " + _SSI_REAL_NOTE),
    ("ABNGNGLAXXX", "Access Bank Plc", "AUD",
     "ANZBAU3MXXX", "ANZ Banking Group",
     "ACCT-17512", "ACCT-29214", "SHA", "spot",
     "Source: Access Bank SwiftCode PDF. " + _SSI_REAL_NOTE),

    # ====================================================================
    # REAL SSI DATA — Saxo Bank A/S Denmark (SAXODK22)
    # Source: home.saxo payment instructions page
    # ====================================================================

    ("SAXODK22XXX", "Saxo Bank A/S", "USD",
     "NADADKKKXXX", "Nordea Bank Danmark",
     "ACCT-19121", "ACCT-17243", "SHA", "spot",
     "Source: Saxo Bank payment instructions page. " + _SSI_REAL_NOTE),
    ("SAXODK22XXX", "Saxo Bank A/S", "EUR",
     "NDEAFIHHXXX", "Nordea Bank Finland",
     "ACCT-19121", "ACCT-82580", "SHA", "spot",
     "Source: Saxo Bank payment instructions page. " + _SSI_REAL_NOTE),
    ("SAXODK22XXX", "Saxo Bank A/S", "GBP",
     "LOYDGB2LXXX", "Lloyds Banking Group",
     "ACCT-19121", "ACCT-35423", "SHA", "spot",
     "Source: Saxo Bank payment instructions page. " + _SSI_REAL_NOTE),
    ("SAXODK22XXX", "Saxo Bank A/S", "DKK",
     "NADADKKKXXX", "Nordea Bank Danmark",
     "ACCT-19121", "ACCT-74839", "SHA", "spot",
     "Source: Saxo Bank payment instructions page. " + _SSI_REAL_NOTE),
    ("SAXODK22XXX", "Saxo Bank A/S", "JPY",
     "BOTKJPJTXXX", "Bank of Tokyo-Mitsubishi UFJ",
     "ACCT-13485", "ACCT-73856", "SHA", "spot",
     "Source: Saxo Bank payment instructions page. " + _SSI_REAL_NOTE),
    ("SAXODK22XXX", "Saxo Bank A/S", "CHF",
     "UBSWCHZH80A", "UBS Switzerland",
     "ACCT-41545", "ACCT-63808", "SHA", "spot",
     "Source: Saxo Bank payment instructions page. " + _SSI_REAL_NOTE),
    ("SAXODK22XXX", "Saxo Bank A/S", "SGD",
     "DBSSSGSXAXX", "DBS Bank Singapore",
     "ACCT-27899", "ACCT-29762", "SHA", "spot",
     "Source: Saxo Bank payment instructions page. " + _SSI_REAL_NOTE),
    ("SAXODK22XXX", "Saxo Bank A/S", "AUD",
     "ANZBAU3MXXX", "ANZ Banking Group",
     "ACCT-17512", "ACCT-01538", "SHA", "spot",
     "Source: Saxo Bank payment instructions page. " + _SSI_REAL_NOTE),
    ("SAXODK22XXX", "Saxo Bank A/S", "CAD",
     "ROYCCAT2XXX", "Royal Bank of Canada",
     "ACCT-38951", "ACCT-99607", "SHA", "spot",
     "Source: Saxo Bank payment instructions page. " + _SSI_REAL_NOTE),
    ("SAXODK22XXX", "Saxo Bank A/S", "SEK",
     "ESSESESSXXX", "Skandinaviska Enskilda Banken",
     "ACCT-41691", "ACCT-09263", "SHA", "spot",
     "Source: Saxo Bank payment instructions page. " + _SSI_REAL_NOTE),
    ("SAXODK22XXX", "Saxo Bank A/S", "NOK",
     "NADADKKKXXX", "Nordea Bank Danmark",
     "ACCT-19121", "ACCT-33635", "SHA", "spot",
     "Source: Saxo Bank payment instructions page. " + _SSI_REAL_NOTE),
    ("SAXODK22XXX", "Saxo Bank A/S", "HKD",
     "HSBCHKHHXXX", "HSBC Hong Kong",
     "ACCT-52623", "ACCT-61728", "SHA", "spot",
     "Source: Saxo Bank payment instructions page. " + _SSI_REAL_NOTE),

    # ====================================================================
    # REAL SSI DATA — MUFG Bank (Europe) N.V. Amsterdam (BOTKNL2A)
    # Source: mufgemea.com SSI page
    # ====================================================================

    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "USD",
     "BOTKUS33XXX", "MUFG Bank Ltd New York",
     "ACCT-40863", "ACCT-47113", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "EUR",
     "BOTKGB2LXXX", "MUFG Bank Ltd London",
     "ACCT-46323", "ACCT-31571", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "GBP",
     "BOTKGB2LXXX", "MUFG Bank Ltd London",
     "ACCT-46323", "ACCT-44053", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "CHF",
     "UBSWCHZH80A", "UBS AG Zurich",
     "ACCT-80284", "ACCT-32687", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "JPY",
     "BOTKJPJTXXX", "MUFG Bank Ltd Tokyo",
     "ACCT-40405", "ACCT-21611", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "CAD",
     "BOTKCATXXXX", "MUFG Bank Ltd Toronto",
     "ACCT-44951", "ACCT-00144", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "AUD",
     "BOTKAU2XXXX", "MUFG Bank Ltd Sydney",
     "ACCT-98730", "ACCT-50292", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "SGD",
     "BOTKSGSXXXX", "MUFG Bank Ltd Singapore",
     "ACCT-54062", "ACCT-00413", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "HKD",
     "BOTKHKHHXXX", "MUFG Bank Ltd Hong Kong",
     "ACCT-58447", "ACCT-45784", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "CNY",
     "BOTKHKHHXXX", "MUFG Bank Ltd Hong Kong",
     "ACCT-96777", "ACCT-04346", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "INR",
     "BOTKINDDXXX", "MUFG Bank Ltd New Delhi",
     "ACCT-52112", "ACCT-91544", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "THB",
     "BOTKTHBXXXX", "Bank of Ayudhya Bangkok",
     "ACCT-05582", "ACCT-64968", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "MYR",
     "BOTKMYKXXXX", "MUFG Bank Malaysia Kuala Lumpur",
     "ACCT-59564", "ACCT-69687", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "MXN",
     "BOTKMXMXXXX", "MUFG Bank SA Mexico City",
     "ACCT-95355", "ACCT-71114", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "AED",
     "BOTKGB2LXXX", "MUFG Bank Ltd London",
     "ACCT-37185", "ACCT-52859", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "SAR",
     "BOTKGB2LXXX", "MUFG Bank Ltd London",
     "ACCT-12086", "ACCT-21939", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "QAR",
     "BOTKGB2LXXX", "MUFG Bank Ltd London",
     "ACCT-34311", "ACCT-04044", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "KWD",
     "BOTKGB2LXXX", "MUFG Bank Ltd London",
     "ACCT-82828", "ACCT-96282", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "BHD",
     "BOTKGB2LXXX", "MUFG Bank Ltd London",
     "ACCT-90716", "ACCT-43038", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "ILS",
     "BOTKGB2LXXX", "MUFG Bank Ltd London",
     "ACCT-10462", "ACCT-80391", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "TRY",
     "BOTKGB2LXXX", "MUFG Bank Ltd London",
     "ACCT-50998", "ACCT-37295", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "MAD",
     "BOTKGB2LXXX", "MUFG Bank Ltd London",
     "ACCT-96934", "ACCT-16834", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "ZAR",
     "SBZAZAJJXXX", "Standard Bank South Africa Johannesburg",
     "ACCT-67925", "ACCT-07431", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "DKK",
     "DABADKKKXXX", "Danske Bank Copenhagen",
     "ACCT-48883", "ACCT-13052", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "SEK",
     "ESSESESSXXX", "SE Banken Stockholm",
     "ACCT-15166", "ACCT-43455", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "NOK",
     "DNBANOKKXXX", "DNB Bank Oslo",
     "ACCT-44907", "ACCT-52904", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "PLN",
     "CITIPLPXXXX", "Bank Handlowy Warsaw",
     "ACCT-92199", "ACCT-89862", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "CZK",
     "CEKOCZPPXXX", "Ceskoslovenska Obchodni Banka Prague",
     "ACCT-55156", "ACCT-25606", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "HUF",
     "BACXHUHBXXX", "UniCredit Bank Hungary Budapest",
     "ACCT-17448", "ACCT-68080", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "RON",
     "BACXROBUXXX", "UniCredit Bank SA Bucharest",
     "ACCT-77984", "ACCT-79948", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),
    ("BOTKNL2AXXX", "MUFG Bank (Europe) N.V. Amsterdam", "KZT",
     "HSBKKZKXXXX", "Halyk Bank Kazakhstan Almaty",
     "ACCT-42328", "ACCT-30755", "SHA", "spot",
     "Source: MUFG EMEA SSI page. " + _SSI_REAL_NOTE),

    # ====================================================================
    # REAL SSI DATA — ICICI Bank UK PLC (ICICGB2L)
    # Source: icicibank.co.uk Nostro & Corresponding Bank PDF
    # ====================================================================

    ("ICICGB2LXXX", "ICICI Bank UK PLC", "USD",
     "CHASUS33XXX", "JPMorgan Chase NY",
     "ACCT-00207", "ACCT-82731", "SHA", "spot",
     "Source: ICICI Bank UK Nostro PDF. " + _SSI_REAL_NOTE),
    ("ICICGB2LXXX", "ICICI Bank UK PLC", "EUR",
     "COBADEFFXXX", "Commerzbank Frankfurt",
     "ACCT-57917", "ACCT-32912", "SHA", "spot",
     "Source: ICICI Bank UK Nostro PDF. " + _SSI_REAL_NOTE),
    ("ICICGB2LXXX", "ICICI Bank UK PLC", "GBP",
     "BARCGB22XXX", "Barclays Bank London",
     "ACCT-17902", "ACCT-22715", "SHA", "spot",
     "Source: ICICI Bank UK Nostro PDF. " + _SSI_REAL_NOTE),
    ("ICICGB2LXXX", "ICICI Bank UK PLC", "CHF",
     "UBSWCHZH80A", "UBS Zurich",
     "ACCT-59505", "ACCT-29049", "SHA", "spot",
     "Source: ICICI Bank UK Nostro PDF. " + _SSI_REAL_NOTE),
    ("ICICGB2LXXX", "ICICI Bank UK PLC", "JPY",
     "BOTKJPJTXXX", "Bank of Tokyo-Mitsubishi UFJ",
     "ACCT-13485", "ACCT-89339", "SHA", "spot",
     "Source: ICICI Bank UK Nostro PDF. " + _SSI_REAL_NOTE),
    ("ICICGB2LXXX", "ICICI Bank UK PLC", "CAD",
     "ROYCCAT2XXX", "Royal Bank of Canada",
     "ACCT-38951", "ACCT-80047", "SHA", "spot",
     "Source: ICICI Bank UK Nostro PDF. " + _SSI_REAL_NOTE),
    ("ICICGB2LXXX", "ICICI Bank UK PLC", "AUD",
     "ANZBAU3MXXX", "ANZ Banking Group",
     "ACCT-17512", "ACCT-30225", "SHA", "spot",
     "Source: ICICI Bank UK Nostro PDF. " + _SSI_REAL_NOTE),
    ("ICICGB2LXXX", "ICICI Bank UK PLC", "SGD",
     "DBSSSGSXAXX", "DBS Bank Singapore",
     "ACCT-27899", "ACCT-55376", "SHA", "spot",
     "Source: ICICI Bank UK Nostro PDF. " + _SSI_REAL_NOTE),
    ("ICICGB2LXXX", "ICICI Bank UK PLC", "HKD",
     "HSBCHKHHXXX", "HSBC Hong Kong",
     "ACCT-52623", "ACCT-25821", "SHA", "spot",
     "Source: ICICI Bank UK Nostro PDF. " + _SSI_REAL_NOTE),
    ("ICICGB2LXXX", "ICICI Bank UK PLC", "AED",
     "ADCBAEAAXXX", "Abu Dhabi Commercial Bank",
     "ACCT-05119", "ACCT-24021", "SHA", "spot",
     "Source: ICICI Bank UK Nostro PDF. " + _SSI_REAL_NOTE),

    # ====================================================================
    # REAL SSI DATA — HDFC Bank India (HDFCINBB)
    # Source: hdfcbank.com nostro correspondent list
    # ====================================================================

    ("HDFCINBBXXX", "HDFC Bank Ltd", "USD",
     "CHASUS33XXX", "JPMorgan Chase NY",
     "ACCT-20900", "ACCT-92540", "SHA", "spot",
     "Source: HDFC Bank correspondent list. " + _SSI_REAL_NOTE),
    ("HDFCINBBXXX", "HDFC Bank Ltd", "USD",
     "CITIUS33XXX", "Citibank NY",
     "ACCT-76369", "ACCT-92540", "SHA", "spot",
     "Source: HDFC Bank correspondent list. " + _SSI_REAL_NOTE),
    ("HDFCINBBXXX", "HDFC Bank Ltd", "GBP",
     "SCBLGB2LXXX", "Standard Chartered London",
     "ACCT-81303", "ACCT-11287", "SHA", "spot",
     "Source: HDFC Bank correspondent list. " + _SSI_REAL_NOTE),
    ("HDFCINBBXXX", "HDFC Bank Ltd", "EUR",
     "COBADEFFXXX", "Commerzbank Frankfurt",
     "ACCT-72579", "ACCT-53522", "SHA", "spot",
     "Source: HDFC Bank correspondent list. " + _SSI_REAL_NOTE),
    ("HDFCINBBXXX", "HDFC Bank Ltd", "SGD",
     "DBSSSGSXAXX", "DBS Bank Singapore",
     "ACCT-47525", "ACCT-85558", "SHA", "spot",
     "Source: HDFC Bank correspondent list. " + _SSI_REAL_NOTE),
    ("HDFCINBBXXX", "HDFC Bank Ltd", "AUD",
     "CTBAAU2SXXX", "Commonwealth Bank Australia",
     "ACCT-15341", "ACCT-36362", "SHA", "spot",
     "Source: HDFC Bank correspondent list. " + _SSI_REAL_NOTE),
    ("HDFCINBBXXX", "HDFC Bank Ltd", "CAD",
     "ROYCCAT2XXX", "Royal Bank of Canada",
     "ACCT-77359", "ACCT-96995", "SHA", "spot",
     "Source: HDFC Bank correspondent list. " + _SSI_REAL_NOTE),

    # ====================================================================
    # REAL SSI DATA — State Bank of India (SBININBB)
    # Source: sbi.bank.in Nostro SSI PDF
    # ====================================================================

    ("SBININBBXXX", "State Bank of India", "USD",
     "BOFAUS3NXXX", "Bank of America New York",
     "ACCT-01905", "ACCT-22883", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "USD",
     "BKTRUS33XXX", "Deutsche Bank Trust NY",
     "ACCT-29096", "ACCT-22883", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "USD",
     "CHASUS33XXX", "JP Morgan Chase NY",
     "ACCT-77591", "ACCT-22883", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "USD",
     "CITIUS33XXX", "Citibank NY",
     "ACCT-99178", "ACCT-22883", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "USD",
     "SCBLUS33XXX", "Standard Chartered NY",
     "ACCT-45858", "ACCT-22883", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "USD",
     "SBINUS33XXX", "SBI New York",
     "ACCT-56531", "ACCT-22883", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "USD",
     "IRVTUS3NXXX", "Bank of NY Mellon",
     "ACCT-91820", "ACCT-22883", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "GBP",
     "NWBKGB2LXXX", "National Westminster Bank London",
     "ACCT-50240", "ACCT-85203", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "GBP",
     "SBINGB2LXXX", "SBI London",
     "ACCT-03274", "ACCT-85203", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "EUR",
     "COBADEFFXXX", "Commerzbank Frankfurt",
     "ACCT-32747", "ACCT-26403", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "EUR",
     "DEUTDEFFXXX", "Deutsche Bank Frankfurt",
     "ACCT-32283", "ACCT-26403", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "EUR",
     "NDEAFIHHXXX", "Nordea Bank Finland Helsinki",
     "ACCT-96181", "ACCT-26403", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "EUR",
     "BBRUBEBBXXX", "ING Belgium Brussels",
     "ACCT-51968", "ACCT-26403", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "EUR",
     "SOGEFRPPXXX", "Societe Generale Paris",
     "ACCT-27712", "ACCT-26403", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "EUR",
     "BBVAESMMXXX", "BBVA Madrid",
     "ACCT-82622", "ACCT-26403", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "EUR",
     "SBINDEFFXXX", "SBI Frankfurt",
     "ACCT-55326", "ACCT-26403", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "JPY",
     "BOTKJPJTXXX", "Bank of Tokyo Mitsubishi Tokyo",
     "ACCT-54257", "ACCT-59819", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "JPY",
     "SBINJPJTXXX", "SBI Tokyo",
     "ACCT-03281", "ACCT-59819", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "CHF",
     "UBSWCHZH80A", "UBS Zurich",
     "ACCT-87329", "ACCT-69958", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "CHF",
     "CRESCHZZ80A", "Credit Suisse Zurich",
     "ACCT-85107", "ACCT-69958", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "CAD",
     "ROYCCAT2XXX", "Royal Bank of Canada Toronto",
     "ACCT-38765", "ACCT-52667", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "CAD",
     "BOFMCAM2XXX", "Bank of Montreal",
     "ACCT-56597", "ACCT-52667", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "AUD",
     "CTBAAU2SXXX", "Commonwealth Bank Australia Sydney",
     "ACCT-64063", "ACCT-91959", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "AUD",
     "NATAAU33XXX", "National Australia Bank Melbourne",
     "ACCT-19225", "ACCT-91959", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "SGD",
     "DBSSSGSGXXX", "DBS Bank Singapore",
     "ACCT-02346", "ACCT-37435", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "HKD",
     "HSBCHKHHXXX", "HSBC Hong Kong",
     "ACCT-70868", "ACCT-25636", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "SAR",
     "NCBKSAJEXXX", "National Commercial Bank Jeddah",
     "ACCT-72219", "ACCT-97173", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "AED",
     "NBADAEAAXXX", "National Bank of Abu Dhabi",
     "ACCT-08204", "ACCT-14387", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "SEK",
     "ESSESESSXXX", "SEB Stockholm",
     "ACCT-18267", "ACCT-08664", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "NOK",
     "DNBANOKKXXX", "DNB Bank Oslo",
     "ACCT-31894", "ACCT-04040", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "DKK",
     "DABADKKKXXX", "Danske Bank Copenhagen",
     "ACCT-14136", "ACCT-30624", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "NZD",
     "BKNZNZ22XXX", "Bank of New Zealand Wellington",
     "ACCT-10959", "ACCT-93194", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "KWD",
     "GULBKWKWXXX", "Gulf Bank Kuwait",
     "ACCT-94791", "ACCT-62164", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "QAR",
     "QNBAQAQAXXX", "Qatar National Bank Doha",
     "ACCT-98503", "ACCT-65817", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "ZAR",
     "SBINZAJJXXX", "SBI Johannesburg",
     "ACCT-96184", "ACCT-00221", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),
    ("SBININBBXXX", "State Bank of India", "KES",
     "BARCKENXXXX", "Barclays Bank Kenya Nairobi",
     "ACCT-52806", "ACCT-62402", "SHA", "spot",
     "Source: SBI Nostro SSI PDF. " + _SSI_REAL_NOTE),

    # ====================================================================
    # REAL SSI DATA — Federal Bank India (FDRLINBBIBD)
    # Source: federal.bank.in correspondent branches page
    # ====================================================================

    ("FDRLINBBIBD", "Federal Bank Ltd", "USD",
     "BOFAUS3NXXX", "Bank of America NY",
     "ACCT-61923", "ACCT-71687", "SHA", "spot",
     "Source: Federal Bank correspondent page. " + _SSI_REAL_NOTE),
    ("FDRLINBBIBD", "Federal Bank Ltd", "USD",
     "CITIUS33XXX", "Citibank NY",
     "ACCT-84479", "ACCT-71687", "SHA", "spot",
     "Source: Federal Bank correspondent page. " + _SSI_REAL_NOTE),
    ("FDRLINBBIBD", "Federal Bank Ltd", "USD",
     "CHASUS33XXX", "JP Morgan Chase NY",
     "ACCT-41019", "ACCT-71687", "SHA", "spot",
     "Source: Federal Bank correspondent page. " + _SSI_REAL_NOTE),
    ("FDRLINBBIBD", "Federal Bank Ltd", "USD",
     "SCBLUS33XXX", "Standard Chartered NY",
     "ACCT-30455", "ACCT-71687", "SHA", "spot",
     "Source: Federal Bank correspondent page. " + _SSI_REAL_NOTE),
    ("FDRLINBBIBD", "Federal Bank Ltd", "EUR",
     "DEUTDEFFXXX", "Deutsche Bank Frankfurt",
     "ACCT-48639", "ACCT-51643", "SHA", "spot",
     "Source: Federal Bank correspondent page. " + _SSI_REAL_NOTE),
    ("FDRLINBBIBD", "Federal Bank Ltd", "EUR",
     "SCBLDEFXXXX", "Standard Chartered Frankfurt",
     "ACCT-37558", "ACCT-51643", "SHA", "spot",
     "Source: Federal Bank correspondent page. " + _SSI_REAL_NOTE),
    ("FDRLINBBIBD", "Federal Bank Ltd", "GBP",
     "SCBLGB2LXXX", "Standard Chartered London",
     "ACCT-75891", "ACCT-03566", "SHA", "spot",
     "Source: Federal Bank correspondent page. " + _SSI_REAL_NOTE),
    ("FDRLINBBIBD", "Federal Bank Ltd", "JPY",
     "SCBLJPJTXXX", "Standard Chartered Tokyo",
     "ACCT-02388", "ACCT-73008", "SHA", "spot",
     "Source: Federal Bank correspondent page. " + _SSI_REAL_NOTE),
    ("FDRLINBBIBD", "Federal Bank Ltd", "CHF",
     "UBSWCHZH80A", "UBS Switzerland",
     "ACCT-86551", "ACCT-10091", "SHA", "spot",
     "Source: Federal Bank correspondent page. " + _SSI_REAL_NOTE),
    ("FDRLINBBIBD", "Federal Bank Ltd", "AUD",
     "ANZBAU3MXXX", "ANZ Australia",
     "ACCT-93114", "ACCT-42813", "SHA", "spot",
     "Source: Federal Bank correspondent page. " + _SSI_REAL_NOTE),
    ("FDRLINBBIBD", "Federal Bank Ltd", "CAD",
     "BOFMCAM2XXX", "BMO Bank of Montreal",
     "ACCT-63509", "ACCT-53689", "SHA", "spot",
     "Source: Federal Bank correspondent page. " + _SSI_REAL_NOTE),
    ("FDRLINBBIBD", "Federal Bank Ltd", "SGD",
     "BOFASG2XXXX", "Bank of America Singapore",
     "ACCT-72536", "ACCT-62547", "SHA", "spot",
     "Source: Federal Bank correspondent page. " + _SSI_REAL_NOTE),
    ("FDRLINBBIBD", "Federal Bank Ltd", "HKD",
     "BOFAHKHXXXX", "Bank of America Hong Kong",
     "ACCT-37311", "ACCT-61118", "SHA", "spot",
     "Source: Federal Bank correspondent page. " + _SSI_REAL_NOTE),
    ("FDRLINBBIBD", "Federal Bank Ltd", "NZD",
     "ANZBNZ22XXX", "ANZ Bank New Zealand",
     "ACCT-87829", "ACCT-84903", "SHA", "spot",
     "Source: Federal Bank correspondent page. " + _SSI_REAL_NOTE),
    ("FDRLINBBIBD", "Federal Bank Ltd", "AED",
     "SCBLAEADXXX", "Standard Chartered Dubai",
     "ACCT-46137", "ACCT-12727", "SHA", "spot",
     "Source: Federal Bank correspondent page. " + _SSI_REAL_NOTE),
    ("FDRLINBBIBD", "Federal Bank Ltd", "SAR",
     "RJHISARIXXX", "Al Rajhi Bank Riyadh",
     "ACCT-39403", "ACCT-03515", "SHA", "spot",
     "Source: Federal Bank correspondent page. " + _SSI_REAL_NOTE),
    ("FDRLINBBIBD", "Federal Bank Ltd", "NOK",
     "DNBANOKKXXX", "DNB Bank ASA",
     "ACCT-25960", "ACCT-60013", "SHA", "spot",
     "Source: Federal Bank correspondent page. " + _SSI_REAL_NOTE),
    ("FDRLINBBIBD", "Federal Bank Ltd", "CNY",
     "SCBLHKHHXXX", "Standard Chartered Hong Kong",
     "ACCT-82838", "ACCT-94995", "SHA", "spot",
     "Source: Federal Bank correspondent page. " + _SSI_REAL_NOTE),

    # ====================================================================
    # REAL SSI DATA — Deutsche Bank AG Seoul (DEUTKRSX)
    # Source: corporates.db.com SSI PDF (March 2025)
    # ====================================================================

    ("DEUTKRSXXXX", "Deutsche Bank AG Seoul", "USD",
     "BKTRUS33XXX", "Deutsche Bank Trust Company Americas NY",
     "ACCT-53167", "ACCT-08548", "SHA", "spot",
     "Source: DB Seoul SSI PDF (Mar 2025). " + _SSI_REAL_NOTE),
    ("DEUTKRSXXXX", "Deutsche Bank AG Seoul", "EUR",
     "DEUTDEFFXXX", "Deutsche Bank AG Frankfurt",
     "ACCT-87947", "ACCT-86563", "SHA", "spot",
     "Source: DB Seoul SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTKRSXXXX", "Deutsche Bank AG Seoul", "JPY",
     "DEUTJPJTXXX", "Deutsche Bank AG Tokyo",
     "ACCT-13485", "ACCT-61977", "SHA", "spot",
     "Source: DB Seoul SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTKRSXXXX", "Deutsche Bank AG Seoul", "GBP",
     "DEUTGB2LXXX", "Deutsche Bank AG London",
     "ACCT-43924", "ACCT-29534", "SHA", "spot",
     "Source: DB Seoul SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTKRSXXXX", "Deutsche Bank AG Seoul", "CHF",
     "DEUTCHZHXXX", "Deutsche Bank AG Zurich",
     "ACCT-03750", "ACCT-21158", "SHA", "spot",
     "Source: DB Seoul SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTKRSXXXX", "Deutsche Bank AG Seoul", "HKD",
     "DEUTHKHHXXX", "Deutsche Bank AG Hong Kong",
     "ACCT-70693", "ACCT-35190", "SHA", "spot",
     "Source: DB Seoul SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTKRSXXXX", "Deutsche Bank AG Seoul", "SGD",
     "DEUTSGSGXXX", "Deutsche Bank AG Singapore",
     "ACCT-76064", "ACCT-36776", "SHA", "spot",
     "Source: DB Seoul SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTKRSXXXX", "Deutsche Bank AG Seoul", "THB",
     "DEUTTHBKXXX", "Deutsche Bank AG Bangkok",
     "ACCT-47559", "ACCT-31906", "SHA", "spot",
     "Source: DB Seoul SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTKRSXXXX", "Deutsche Bank AG Seoul", "NZD",
     "DEUTNZ2AXXX", "Deutsche Bank AG Wellington",
     "ACCT-48653", "ACCT-06894", "SHA", "spot",
     "Source: DB Seoul SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTKRSXXXX", "Deutsche Bank AG Seoul", "SEK",
     "DEUTSESSXXX", "Deutsche Bank AG Stockholm",
     "ACCT-41727", "ACCT-09908", "SHA", "spot",
     "Source: DB Seoul SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTKRSXXXX", "Deutsche Bank AG Seoul", "NOK",
     "DEUTNOKKXXX", "Deutsche Bank AG Oslo",
     "ACCT-74841", "ACCT-42507", "SHA", "spot",
     "Source: DB Seoul SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTKRSXXXX", "Deutsche Bank AG Seoul", "DKK",
     "DEUTDKKKXXX", "Deutsche Bank AG Copenhagen",
     "ACCT-74508", "ACCT-47061", "SHA", "spot",
     "Source: DB Seoul SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTKRSXXXX", "Deutsche Bank AG Seoul", "TWD",
     "DEUTTWTWXXX", "Deutsche Bank AG Taipei",
     "ACCT-03124", "ACCT-03712", "SHA", "spot",
     "Source: DB Seoul SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTKRSXXXX", "Deutsche Bank AG Seoul", "INR",
     "DEUTINBBXXX", "Deutsche Bank AG India",
     "ACCT-59656", "ACCT-33969", "SHA", "spot",
     "Source: DB Seoul SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTKRSXXXX", "Deutsche Bank AG Seoul", "CNY",
     "DEUTCNSHXXX", "Deutsche Bank AG China Shanghai",
     "ACCT-44594", "ACCT-69542", "SHA", "spot",
     "Source: DB Seoul SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTKRSXXXX", "Deutsche Bank AG Seoul", "CAD",
     "DEUTCAFFXXX", "Deutsche Bank AG Toronto",
     "ACCT-44600", "ACCT-51912", "SHA", "spot",
     "Source: DB Seoul SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTKRSXXXX", "Deutsche Bank AG Seoul", "AUD",
     "DEUTAU2SXXX", "Deutsche Bank AG Sydney",
     "ACCT-78813", "ACCT-54988", "SHA", "spot",
     "Source: DB Seoul SSI PDF. " + _SSI_REAL_NOTE),
    ("DEUTKRSXXXX", "Deutsche Bank AG Seoul", "KRW",
     "DEUTKRSXXXX", "Deutsche Bank AG Seoul",
     "ACCT-17553", "ACCT-28421", "SHA", "spot",
     "Source: DB Seoul SSI PDF. " + _SSI_REAL_NOTE),

    # ====================================================================
    # REAL SSI DATA — European Depositary Bank SA Luxembourg (EDBBEB22)
    # Source: europeandepositarybank.com SSI page
    # ====================================================================

    ("EDBBEB22XXX", "European Depositary Bank SA", "USD",
     "IRVTUS3NXXX", "BNY Mellon",
     "ACCT-58552", "ACCT-99813", "SHA", "spot",
     "Source: EDB SSI page. " + _SSI_REAL_NOTE),
    ("EDBBEB22XXX", "European Depositary Bank SA", "EUR",
     "IRVTBE99XXX", "BNY Mellon Brussels",
     "ACCT-49234", "ACCT-30171", "SHA", "spot",
     "Source: EDB SSI page. " + _SSI_REAL_NOTE),
    ("EDBBEB22XXX", "European Depositary Bank SA", "GBP",
     "SBOSGB2LXXX", "State Street Bank London",
     "ACCT-30708", "ACCT-86279", "SHA", "spot",
     "Source: EDB SSI page. " + _SSI_REAL_NOTE),
    ("EDBBEB22XXX", "European Depositary Bank SA", "JPY",
     "IRVTJPJTXXX", "BNY Mellon Japan",
     "ACCT-62880", "ACCT-23558", "SHA", "spot",
     "Source: EDB SSI page. " + _SSI_REAL_NOTE),
    ("EDBBEB22XXX", "European Depositary Bank SA", "AUD",
     "SCBLAU2SXXX", "Standard Chartered Australia",
     "ACCT-76706", "ACCT-71519", "SHA", "spot",
     "Source: EDB SSI page. " + _SSI_REAL_NOTE),
    ("EDBBEB22XXX", "European Depositary Bank SA", "CAD",
     "IRVTUS3NXXX", "BNY Mellon cross-ccy",
     "ACCT-58552", "ACCT-21513", "SHA", "spot",
     "Source: EDB SSI page. " + _SSI_REAL_NOTE),

    # ====================================================================
    # REAL SSI DATA — Global IME Bank Ltd Nepal (GLBBNPKA)
    # Source: globalimebank.com international correspondent page
    # ====================================================================

    ("GLBBNPKAXXX", "Global IME Bank Ltd", "USD",
     "SCBLUS33XXX", "Standard Chartered NY",
     "ACCT-27892", "ACCT-61770", "SHA", "spot",
     "Source: Global IME Bank correspondent page. " + _SSI_REAL_NOTE),
    ("GLBBNPKAXXX", "Global IME Bank Ltd", "USD",
     "CITIUS33XXX", "Citibank NY",
     "ACCT-73814", "ACCT-61770", "SHA", "spot",
     "Source: Global IME Bank correspondent page. " + _SSI_REAL_NOTE),
    ("GLBBNPKAXXX", "Global IME Bank Ltd", "USD",
     "BOMLUS33XXX", "Mashreqbank NY",
     "ACCT-86955", "ACCT-61770", "SHA", "spot",
     "Source: Global IME Bank correspondent page. " + _SSI_REAL_NOTE),
    ("GLBBNPKAXXX", "Global IME Bank Ltd", "EUR",
     "COBADEFFXXX", "Commerzbank Frankfurt",
     "ACCT-72579", "ACCT-94555", "SHA", "spot",
     "Source: Global IME Bank correspondent page. " + _SSI_REAL_NOTE),
    ("GLBBNPKAXXX", "Global IME Bank Ltd", "EUR",
     "DEUTDEFFXXX", "Deutsche Bank Frankfurt",
     "ACCT-87947", "ACCT-94555", "SHA", "spot",
     "Source: Global IME Bank correspondent page. " + _SSI_REAL_NOTE),
    ("GLBBNPKAXXX", "Global IME Bank Ltd", "GBP",
     "SCBLGB2LXXX", "Standard Chartered London",
     "ACCT-88609", "ACCT-37317", "SHA", "spot",
     "Source: Global IME Bank correspondent page. " + _SSI_REAL_NOTE),
    ("GLBBNPKAXXX", "Global IME Bank Ltd", "CHF",
     "UBSWCHZH80A", "UBS Zurich",
     "ACCT-59505", "ACCT-81678", "SHA", "spot",
     "Source: Global IME Bank correspondent page. " + _SSI_REAL_NOTE),
    ("GLBBNPKAXXX", "Global IME Bank Ltd", "JPY",
     "BOTKJPJTXXX", "Bank of Tokyo-Mitsubishi UFJ",
     "ACCT-40405", "ACCT-46941", "SHA", "spot",
     "Source: Global IME Bank correspondent page. " + _SSI_REAL_NOTE),
    ("GLBBNPKAXXX", "Global IME Bank Ltd", "AUD",
     "ANZBAU3MXXX", "ANZ Melbourne",
     "ACCT-17512", "ACCT-48692", "SHA", "spot",
     "Source: Global IME Bank correspondent page. " + _SSI_REAL_NOTE),
    ("GLBBNPKAXXX", "Global IME Bank Ltd", "CAD",
     "ROYCCAT2XXX", "Royal Bank of Canada",
     "ACCT-38951", "ACCT-27324", "SHA", "spot",
     "Source: Global IME Bank correspondent page. " + _SSI_REAL_NOTE),
    ("GLBBNPKAXXX", "Global IME Bank Ltd", "THB",
     "BKKBTHBKXXX", "Bangkok Bank",
     "ACCT-29298", "ACCT-05796", "SHA", "spot",
     "Source: Global IME Bank correspondent page. " + _SSI_REAL_NOTE),
    ("GLBBNPKAXXX", "Global IME Bank Ltd", "AED",
     "BOMLAEADXXX", "Mashreqbank Dubai",
     "ACCT-37438", "ACCT-73737", "SHA", "spot",
     "Source: Global IME Bank correspondent page. " + _SSI_REAL_NOTE),
    ("GLBBNPKAXXX", "Global IME Bank Ltd", "SGD",
     "DBSSSGSXAXX", "DBS Bank Singapore",
     "ACCT-27899", "ACCT-79312", "SHA", "spot",
     "Source: Global IME Bank correspondent page. " + _SSI_REAL_NOTE),

    # ====================================================================
    # REAL SSI DATA — Tamilnad Mercantile Bank (TMBLINDIA)
    # Source: tmb.bank.in Nostro Remittance Account page
    # ====================================================================

    ("TMBLINDIXXX", "Tamilnad Mercantile Bank", "USD",
     "CHASUS33XXX", "JP Morgan Chase NY",
     "ACCT-41019", "ACCT-74471", "SHA", "spot",
     "Source: TMB Bank nostro remittance page. " + _SSI_REAL_NOTE),
    ("TMBLINDIXXX", "Tamilnad Mercantile Bank", "EUR",
     "COBADEFFXXX", "Commerzbank Frankfurt",
     "ACCT-44066", "ACCT-88297", "SHA", "spot",
     "Source: TMB Bank nostro remittance page. " + _SSI_REAL_NOTE),
    ("TMBLINDIXXX", "Tamilnad Mercantile Bank", "GBP",
     "SCBLGB2LXXX", "Standard Chartered London",
     "ACCT-88609", "ACCT-58761", "SHA", "spot",
     "Source: TMB Bank nostro remittance page. " + _SSI_REAL_NOTE),
    ("TMBLINDIXXX", "Tamilnad Mercantile Bank", "CAD",
     "ROYCCAT2XXX", "Royal Bank of Canada",
     "ACCT-38951", "ACCT-13817", "SHA", "spot",
     "Source: TMB Bank nostro remittance page. " + _SSI_REAL_NOTE),
    ("TMBLINDIXXX", "Tamilnad Mercantile Bank", "AUD",
     "CTBAAU2SXXX", "Commonwealth Bank Australia",
     "ACCT-15341", "ACCT-82451", "SHA", "spot",
     "Source: TMB Bank nostro remittance page. " + _SSI_REAL_NOTE),
    ("TMBLINDIXXX", "Tamilnad Mercantile Bank", "SGD",
     "DBSSSGSXAXX", "DBS Bank Singapore",
     "ACCT-47525", "ACCT-38112", "SHA", "spot",
     "Source: TMB Bank nostro remittance page. " + _SSI_REAL_NOTE),
    ("TMBLINDIXXX", "Tamilnad Mercantile Bank", "AED",
     "BOMLAEADXXX", "Mashreqbank Dubai",
     "ACCT-37438", "ACCT-66163", "SHA", "spot",
     "Source: TMB Bank nostro remittance page. " + _SSI_REAL_NOTE),

    # ====================================================================
    # REAL SSI DATA — IDFC FIRST Bank India (IDFBINBBMUM)
    # Source: idfcfirst.bank.in inward remittance bank details
    # ====================================================================

    ("IDFBINBBXXX", "IDFC FIRST Bank", "USD",
     "CHASUS33XXX", "JP Morgan Chase NY",
     "ACCT-20900", "ACCT-06856", "SHA", "spot",
     "Source: IDFC FIRST Bank inward remittance page. " + _SSI_REAL_NOTE),
    ("IDFBINBBXXX", "IDFC FIRST Bank", "USD",
     "CITIUS33XXX", "Citibank NY",
     "ACCT-76369", "ACCT-06856", "SHA", "spot",
     "Source: IDFC FIRST Bank inward remittance page. " + _SSI_REAL_NOTE),
    ("IDFBINBBXXX", "IDFC FIRST Bank", "USD",
     "IRVTUS3NXXX", "Bank of NY Mellon",
     "ACCT-56572", "ACCT-06856", "SHA", "spot",
     "Source: IDFC FIRST Bank inward remittance page. " + _SSI_REAL_NOTE),
    ("IDFBINBBXXX", "IDFC FIRST Bank", "EUR",
     "COBADEFFXXX", "Commerzbank Frankfurt",
     "ACCT-72579", "ACCT-65773", "SHA", "spot",
     "Source: IDFC FIRST Bank inward remittance page. " + _SSI_REAL_NOTE),
    ("IDFBINBBXXX", "IDFC FIRST Bank", "GBP",
     "SCBLGB2LXXX", "Standard Chartered London",
     "ACCT-88609", "ACCT-32446", "SHA", "spot",
     "Source: IDFC FIRST Bank inward remittance page. " + _SSI_REAL_NOTE),
    ("IDFBINBBXXX", "IDFC FIRST Bank", "CHF",
     "UBSWCHZH80A", "UBS Zurich",
     "ACCT-86551", "ACCT-64429", "SHA", "spot",
     "Source: IDFC FIRST Bank inward remittance page. " + _SSI_REAL_NOTE),
    ("IDFBINBBXXX", "IDFC FIRST Bank", "JPY",
     "MHCBJPJTXXX", "Mizuho Bank Tokyo",
     "ACCT-85192", "ACCT-54524", "SHA", "spot",
     "Source: IDFC FIRST Bank inward remittance page. " + _SSI_REAL_NOTE),
    ("IDFBINBBXXX", "IDFC FIRST Bank", "AUD",
     "CTBAAU2SXXX", "Commonwealth Bank Australia",
     "ACCT-15341", "ACCT-46120", "SHA", "spot",
     "Source: IDFC FIRST Bank inward remittance page. " + _SSI_REAL_NOTE),
    ("IDFBINBBXXX", "IDFC FIRST Bank", "CAD",
     "ROYCCAT2XXX", "Royal Bank of Canada",
     "ACCT-38951", "ACCT-26877", "SHA", "spot",
     "Source: IDFC FIRST Bank inward remittance page. " + _SSI_REAL_NOTE),
    ("IDFBINBBXXX", "IDFC FIRST Bank", "SGD",
     "DBSSSGSXAXX", "DBS Bank Singapore",
     "ACCT-47525", "ACCT-76085", "SHA", "spot",
     "Source: IDFC FIRST Bank inward remittance page. " + _SSI_REAL_NOTE),
    ("IDFBINBBXXX", "IDFC FIRST Bank", "AED",
     "BOMLAEADXXX", "Mashreqbank Dubai",
     "ACCT-37438", "ACCT-81930", "SHA", "spot",
     "Source: IDFC FIRST Bank inward remittance page. " + _SSI_REAL_NOTE),
    ("IDFBINBBXXX", "IDFC FIRST Bank", "HKD",
     "HSBCHKHHXXX", "HSBC Hong Kong",
     "ACCT-52623", "ACCT-26310", "SHA", "spot",
     "Source: IDFC FIRST Bank inward remittance page. " + _SSI_REAL_NOTE),
]


# ---------------------------------------------------------------------------
# Account registry — synthetic account-holder records for VoP.
# Each tuple: (iban, account_holder_name, bic, country_code, account_type)
#
# ⚠️  IBANs are synthetic (valid checksums via schwifty where possible,
# but not linked to real accounts). Used only for VoP development/testing.
# ---------------------------------------------------------------------------

ACCOUNT_RECORDS = [
    # UK personal accounts (CoP-compatible test IBANs)
    ("GB29NWBK60161331926819", "John Smith", "NWBKGB2L", "GB", "personal"),
    ("GB29NWBK60161331926820", "Acme Trading Ltd", "NWBKGB2L", "GB", "business"),
    ("GB29NWBK60161331926821", "Maria Garcia", "NWBKGB2L", "GB", "personal"),
    ("GB29NWBK60161331926822", "James O'Connor", "NWBKGB2L", "GB", "personal"),
    # German personal/business
    ("DE89370400440532013000", "Hans Mueller", "COBADEFF", "DE", "personal"),
    ("DE89370400440532013001", "Schmidt GmbH", "COBADEFF", "DE", "business"),
    # French
    ("FR1420041010050500013M02606", "Pierre Dupont", "BNPAFRPP", "FR", "personal"),
    # Nigerian (synthetic — NG IBANs are 15 chars: NGA + check + bank code + account)
    ("NG3705000012345678901234", "Olaniyi Oladokun", "GTBINGLA", "NG", "personal"),
    ("NG3705000012345678901235", "Lagos Trading Co", "GTBINGLA", "NG", "business"),
    # UAE
    ("AE260331234567890123456", "Ahmed Al Mansouri", "EBILAEAD", "AE", "personal"),
    # India (synthetic — IN doesn't use IBAN, but we store a mock format)
    ("IN12345678901234567890", "Rajesh Kumar", "HDFCINBB", "IN", "personal"),
    # Canada (synthetic — CA doesn't use IBAN, stored in mock IBAN-like format)
    ("CA12345678901234567890", "Marie Tremblay", "ROYCCAT2", "CA", "personal"),
    ("CA12345678901234567891", "Maple Leaf Trading Inc", "BOFMCAM2", "CA", "business"),
    ("CA12345678901234567892", "Wei Chen", "CIBCCATT", "CA", "personal"),
]


# ---------------------------------------------------------------------------
# Lift-fee table — per-corridor intermediary fees for the Fee Calculator.
#
# Each tuple: (intermediary_bic, intermediary_name, currency, fee_amount, fee_type)
#
# fee_type: "flat" (fixed amount per hop) or "pct" (percentage of amount)
# These are ILLUSTRATIVE — real lift fees are bilateral and confidential.
# ---------------------------------------------------------------------------

LIFT_FEES = [
    # USD correspondents
    ("CITIUS33XXX", "Citibank N.A.", "USD", 15.00, "flat"),
    ("BOFAUS3NXXX", "Bank of America", "USD", 12.50, "flat"),
    ("CHASUS33XXX", "JPMorgan Chase", "USD", 10.00, "flat"),
    ("SCBLUS33XXX", "Standard Chartered NY", "USD", 18.00, "flat"),
    ("IRVTUS3NXXX", "BNY Mellon", "USD", 20.00, "flat"),
    # GBP clearing
    ("BARCGB22XXX", "Barclays", "GBP", 10.00, "flat"),
    ("NWBKGB2LXXX", "NatWest", "GBP", 8.00, "flat"),
    ("SCBLGB2LXXX", "Standard Chartered London", "GBP", 12.00, "flat"),
    # EUR clearing
    ("COBADEFFXXX", "Commerzbank", "EUR", 8.00, "flat"),
    ("DEUTDEFFXXX", "Deutsche Bank", "EUR", 10.00, "flat"),
    ("BNPAFRPPXXX", "BNP Paribas", "EUR", 9.00, "flat"),
    # JPY
    ("BOTKJPJTXXX", "MUFG (BoT)", "JPY", 2000, "flat"),
    ("SMBCJPJTXXX", "SMBC", "JPY", 1500, "flat"),
    # General fallback for unknown intermediaries — one per currency
    ("GENERIC", "Intermediary Bank", "USD", 15.00, "flat"),
    ("GENERIC", "Intermediary Bank", "GBP", 10.00, "flat"),
    ("GENERIC", "Intermediary Bank", "EUR", 10.00, "flat"),
    ("GENERIC", "Intermediary Bank", "JPY", 2000, "flat"),
    ("GENERIC", "Intermediary Bank", "NGN", 1000, "flat"),
    ("GENERIC", "Intermediary Bank", "INR", 500, "flat"),
    ("GENERIC", "Intermediary Bank", "AED", 50, "flat"),
    ("GENERIC", "Intermediary Bank", "KES", 1500, "flat"),
    ("GENERIC", "Intermediary Bank", "CAD", 15.00, "flat"),
    ("GENERIC", "Intermediary Bank", "AUD", 20.00, "flat"),
    ("GENERIC", "Intermediary Bank", "SGD", 20.00, "flat"),
    ("GENERIC", "Intermediary Bank", "HKD", 150, "flat"),
    ("GENERIC", "Intermediary Bank", "CHF", 15.00, "flat"),
    ("GENERIC", "Intermediary Bank", "SAR", 50, "flat"),
    ("GENERIC", "Intermediary Bank", "ZAR", 200, "flat"),
]


def seed_if_empty(session) -> dict:
    """Idempotently seed the directory + rules + SSIs + accounts if empty."""
    inserted = {"banks": 0, "corridor_rules": 0, "ssi": 0, "accounts": 0}

    if session.query(Bank).count() == 0:
        for row in BANKS:
            bic, name, cc, city, cur = row
            session.add(
                Bank(
                    bic=bic,
                    bank_name=name,
                    country_code=cc,
                    city=city,
                    country_currency=cur,
                )
            )
        inserted["banks"] = len(BANKS)

    if session.query(CorridorRule).count() == 0:
        for row in CORRIDOR_RULES:
            ccy, ctry, bic, name, corr, conf, rank = row
            session.add(
                CorridorRule(
                    destination_currency=ccy,
                    destination_country=ctry,
                    intermediary_bic=bic,
                    intermediary_name=name,
                    corridor=corr,
                    confidence=conf,
                    rank=rank,
                )
            )
        inserted["corridor_rules"] = len(CORRIDOR_RULES)

    if session.query(SSI).count() == 0:
        for row in SSI_RECORDS:
            (ben_bic, ben_name, ccy, int_bic, int_name,
             int_acct, ben_acct, charge, vdate, notes) = row
            session.add(
                SSI(
                    beneficiary_bic=ben_bic,
                    beneficiary_bank_name=ben_name,
                    currency=ccy,
                    intermediary_bic=int_bic,
                    intermediary_bank_name=int_name,
                    intermediary_account=int_acct,
                    beneficiary_account=ben_acct,
                    charge_code=charge,
                    value_date=vdate,
                    notes=notes,
                )
            )
        inserted["ssi"] = len(SSI_RECORDS)

    if session.query(Account).count() == 0:
        for row in ACCOUNT_RECORDS:
            iban, name, bic, cc, atype = row
            session.add(
                Account(
                    iban=iban,
                    account_holder_name=name,
                    bic=bic,
                    country_code=cc,
                    account_type=atype,
                )
            )
        inserted["accounts"] = len(ACCOUNT_RECORDS)

    session.commit()
    return inserted
