"""baseline

Revision ID: 914225a8c624
Revises: 
Create Date: 2026-07-15 22:44:39.493420

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '914225a8c624'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('account_holder_name', sa.String(length=200), nullable=False),
    sa.Column('bic', sa.String(length=11), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_country_code'), 'accounts', ['country_code'], unique=False)
    op.create_index(op.f('ix_accounts_iban'), 'accounts', ['iban'], unique=True)
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bic', sa.String(length=11), nullable=False),
    sa.Column('bank_name', sa.String(length=200), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country_currency', sa.String(length=3), nullable=True),
    sa.Column('swift_active', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banks_bic'), 'banks', ['bic'], unique=True)
    op.create_index('ix_banks_country', 'banks', ['country_code'], unique=False)
    op.create_index(op.f('ix_banks_country_code'), 'banks', ['country_code'], unique=False)
    op.create_table('corridor_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_currency', sa.String(length=3), nullable=False),
    sa.Column('destination_country', sa.String(length=2), nullable=True),
    sa.Column('intermediary_bic', sa.String(length=11), nullable=False),
    sa.Column('intermediary_name', sa.String(length=200), nullable=False),
    sa.Column('corridor', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_corridor_ccy_country', 'corridor_rules', ['destination_currency', 'destination_country'], unique=False)
    op.create_index(op.f('ix_corridor_rules_destination_currency'), 'corridor_rules', ['destination_currency'], unique=False)
    op.create_table('fedach_banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routing_number', sa.String(length=9), nullable=False),
    sa.Column('office_code', sa.String(length=1), nullable=True),
    sa.Column('servicing_frb_number', sa.String(length=9), nullable=True),
    sa.Column('record_type_code', sa.String(length=1), nullable=True),
    sa.Column('revised', sa.String(length=1), nullable=True),
    sa.Column('customer_name', sa.String(length=36), nullable=True),
    sa.Column('address', sa.String(length=36), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=9), nullable=True),
    sa.Column('zip_extension', sa.String(length=4), nullable=True),
    sa.Column('phone_area_code', sa.String(length=3), nullable=True),
    sa.Column('phone_prefix', sa.String(length=3), nullable=True),
    sa.Column('phone_suffix', sa.String(length=4), nullable=True),
    sa.Column('status_code', sa.String(length=1), nullable=True),
    sa.Column('view_code', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fedach_banks_routing_number'), 'fedach_banks', ['routing_number'], unique=False)
    op.create_index('ix_fedach_rtn', 'fedach_banks', ['routing_number'], unique=False)
    op.create_table('fedwire_banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routing_number', sa.String(length=9), nullable=False),
    sa.Column('telegraphic_name', sa.String(length=18), nullable=True),
    sa.Column('customer_name', sa.String(length=36), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=25), nullable=True),
    sa.Column('funds_transfer', sa.String(length=1), nullable=True),
    sa.Column('settlement_only', sa.String(length=1), nullable=True),
    sa.Column('book_entry', sa.String(length=1), nullable=True),
    sa.Column('date_of_last_revision', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fedwire_banks_routing_number'), 'fedwire_banks', ['routing_number'], unique=False)
    op.create_index('ix_fedwire_rtn', 'fedwire_banks', ['routing_number'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uetr', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bank_bic', sa.String(length=11), nullable=False),
    sa.Column('bank_name', sa.String(length=200), nullable=True),
    sa.Column('hop', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('charge_code', sa.String(length=3), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('instructing_bic', sa.String(length=11), nullable=True),
    sa.Column('instructed_bic', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_events_uetr'), 'payment_events', ['uetr'], unique=False)
    op.create_index('ix_payment_uetr_hop', 'payment_events', ['uetr', 'hop'], unique=False)
    op.create_table('ssi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_bic', sa.String(length=11), nullable=False),
    sa.Column('beneficiary_bank_name', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('intermediary_bic', sa.String(length=11), nullable=False),
    sa.Column('intermediary_bank_name', sa.String(length=200), nullable=True),
    sa.Column('intermediary_account', sa.String(length=34), nullable=True),
    sa.Column('beneficiary_account', sa.String(length=34), nullable=True),
    sa.Column('charge_code', sa.String(length=3), nullable=True),
    sa.Column('value_date', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beneficiary_bic', 'currency', 'intermediary_bic', name='uq_ssi_composite')
    )
    op.create_index(op.f('ix_ssi_beneficiary_bic'), 'ssi', ['beneficiary_bic'], unique=False)
    op.create_index('ix_ssi_bic_ccy', 'ssi', ['beneficiary_bic', 'currency'], unique=False)
    op.create_index(op.f('ix_ssi_currency'), 'ssi', ['currency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ssi_currency'), table_name='ssi')
    op.drop_index('ix_ssi_bic_ccy', table_name='ssi')
    op.drop_index(op.f('ix_ssi_beneficiary_bic'), table_name='ssi')
    op.drop_table('ssi')
    op.drop_index('ix_payment_uetr_hop', table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_uetr'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index('ix_fedwire_rtn', table_name='fedwire_banks')
    op.drop_index(op.f('ix_fedwire_banks_routing_number'), table_name='fedwire_banks')
    op.drop_table('fedwire_banks')
    op.drop_index('ix_fedach_rtn', table_name='fedach_banks')
    op.drop_index(op.f('ix_fedach_banks_routing_number'), table_name='fedach_banks')
    op.drop_table('fedach_banks')
    op.drop_index(op.f('ix_corridor_rules_destination_currency'), table_name='corridor_rules')
    op.drop_index('ix_corridor_ccy_country', table_name='corridor_rules')
    op.drop_table('corridor_rules')
    op.drop_index(op.f('ix_banks_country_code'), table_name='banks')
    op.drop_index('ix_banks_country', table_name='banks')
    op.drop_index(op.f('ix_banks_bic'), table_name='banks')
    op.drop_table('banks')
    op.drop_index(op.f('ix_accounts_iban'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_country_code'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
