#!/usr/bin/env python3
"""Re-check every SSI evidence file against the source it cites.

CI attests exactly one evidence file.  Every other cited source can move, or
stop existing, without anything going red — so the only way to know the state
of the evidence set is to go and look.

This sweep reports, per file, what could actually be established:

``verified``
    digest matched, route keys matched, every account fingerprint matched.
``unreadable``
    the digest could be checked, the routes could not.  The extractor reads
    HTML tables; most cited sources are PDFs.  This is emphatically *not* a
    finding of drift — an empty extraction resembles total turnover, and
    reporting it as such would send someone chasing a change that never
    happened.
``digest-changed``
    the bytes moved, while the routes and accounts that could be read still
    match.  Not ``verified``: the first of the three checks failed, and a
    survey that calls that verified teaches people to shrug at digests.
``no-fingerprints``
    the evidence records routes but never captured the accounts behind them,
    so an account could move under an unchanged route key unnoticed.  This is
    a gap in the evidence, not in the source.
``no-routes``
    the evidence pins a digest but records nothing about the page's contents,
    so there is nothing to compare.
``duplicate-routes``
    the source lists one currency/BIC twice with different accounts, so which
    row is the settlement instruction is genuinely ambiguous.
``accounts-changed`` / ``routes-changed``
    a real discrepancy.  Both are reported together when both occur; a route
    the source no longer carries is a route-key finding only, never counted a
    second time as an account move.
``unattested``
    no digest was ever captured; the citation is a URL and a promise.
``fetch-failed``
    the source did not answer.  A 404 means the citation is dead; several of
    these hosts also fail intermittently on TLS or gateway errors, so counts
    move between runs.

The sweep does not guess why a digest moved — for a PDF regenerated by a
bank's CMS it usually means the bytes changed, not the settlement
instructions — and it writes nothing.  Deciding what a change means is the
operator's job.

Usage:
    python scripts/ssi-autopilot/sweep_source_attestations.py
    python scripts/ssi-autopilot/sweep_source_attestations.py --json
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import sys
from pathlib import Path
from typing import Callable, Iterable

ROOT = Path(__file__).resolve().parents[2]
EVIDENCE_DIR = ROOT / "scripts/ssi-autopilot/evidence"


def _load_attestation():
    path = Path(__file__).resolve().parent / "verify_source_attestation.py"
    spec = importlib.util.spec_from_file_location("ssi_source_attestation", path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


attestation = _load_attestation()


def _classify(
    evidence: dict, source_bytes: bytes, digest_matches: bool
) -> tuple[str, bool, str]:
    """Return (status, routes_checked, detail) for a source that was fetched.

    Each refusal is caught by type. Matching on message text conflated a
    source the extractor cannot parse with an evidence file that is missing
    fields — reporting a schema defect as a benign PDF limitation, which is
    the kind of miscount that makes a survey worse than no survey.
    """
    try:
        report = attestation.compare(evidence, source_bytes)
    except attestation.EvidenceWithoutRoutes:
        return "no-routes", False, "evidence records no routes"
    except attestation.EvidenceWithoutFingerprints:
        return (
            "no-fingerprints",
            False,
            "evidence records routes but not the accounts behind them",
        )
    except attestation.UnreadableSource:
        return (
            "unreadable",
            False,
            "extractor reads HTML tables; this source is not one",
        )
    except attestation.DuplicateRouteKey as exc:
        return "duplicate-routes", False, str(exc).splitlines()[0][:80]
    except attestation.AttestationError as exc:
        return "error", False, str(exc).splitlines()[0][:80]

    # More than one category can change at once, and reporting only the more
    # severe one hides the rest.
    problems = []
    if not report["route_keys"]["match"]:
        keys = report["route_keys"]
        problems.append(f"{keys['actual']} of {keys['expected']} route keys matched")
    if report["fingerprints"]["changed"]:
        moved = ", ".join(
            f"{route['currency']}/{route['int_bic']}"
            for route in report["fingerprints"]["changed"]
        )
        problems.append(f"accounts moved: {moved}")
    if problems:
        status = (
            "accounts-changed"
            if report["fingerprints"]["changed"]
            else "routes-changed"
        )
        return status, True, "; ".join(problems)
    detail = (
        f"{report['route_keys']['actual']} routes, "
        f"{report['fingerprints']['matched']} fingerprints"
    )
    # "verified" means all three checks passed. A source whose bytes moved has
    # failed the first one, however intact its routes look, and calling that
    # verified invites exactly the shrug this tooling exists to stop.
    if not digest_matches:
        return "digest-changed", True, f"routes and accounts intact; {detail}"
    return "verified", True, detail


def sweep(
    paths: Iterable[Path],
    fetch: Callable[[str], bytes] | None = None,
) -> list[dict]:
    """Check each evidence file against its cited source.

    `fetch` is injected so the sweep is testable without a network, and so an
    operator can point it at a cache.
    """
    fetcher = fetch or attestation._fetch
    results: list[dict] = []
    for path in paths:
        evidence = json.loads(path.read_text(encoding="utf-8"))
        result = {
            "file": path.name,
            "source": attestation.redact_url(evidence.get("source", "")),
            "digest": "absent",
            "status": "unattested",
            "routes_checked": False,
            "detail": "no source_sha256 was ever captured",
        }
        if "source_sha256" not in evidence:
            results.append(result)
            continue
        try:
            source_bytes = fetcher(evidence["source"])
        except Exception as exc:  # noqa: BLE001 - one dead source must not end the sweep
            result.update(
                digest="unknown",
                status="fetch-failed",
                detail=f"{type(exc).__name__}: {exc}",
            )
            results.append(result)
            continue

        digest = hashlib.sha256(
            attestation._canonical_source_bytes(source_bytes)
        ).hexdigest()
        digest_matches = digest == evidence["source_sha256"]
        status, routes_checked, detail = _classify(
            evidence, source_bytes, digest_matches
        )
        result.update(
            digest="match" if digest_matches else "changed",
            status=status,
            routes_checked=routes_checked,
            detail=detail,
        )
        results.append(result)
    return results


def _render(results: list[dict]) -> str:
    width = max((len(result["file"]) for result in results), default=4)
    lines = [f"{'file'.ljust(width)}  {'digest':8}  {'status':16}  detail"]
    for result in results:
        lines.append(
            f"{result['file'].ljust(width)}  {result['digest']:8}  "
            f"{result['status']:16}  {result['detail']}"
        )
    tally: dict[str, int] = {}
    for result in results:
        tally[result["status"]] = tally.get(result["status"], 0) + 1
        tally["digest:" + result["digest"]] = tally.get("digest:" + result["digest"], 0) + 1
    lines.append("")
    for key in sorted(tally):
        lines.append(f"  {key:22} {tally[key]}")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--evidence-dir", type=Path, default=EVIDENCE_DIR)
    parser.add_argument("--json", action="store_true", help="emit machine-readable output")
    args = parser.parse_args()

    results = sweep(sorted(args.evidence_dir.glob("*.json")))
    print(json.dumps(results, indent=2) if args.json else _render(results))
    return 0


if __name__ == "__main__":
    sys.exit(main())
