#!/usr/bin/env python3
"""Re-check every SSI evidence file against the source it cites.

CI attests exactly one evidence file.  Every other cited source can move, or
stop existing, without anything going red — so the only way to know the state
of the evidence set is to go and look.

This sweep reports, per file, what could actually be established:

``verified``
    digest matched, route keys matched, every account fingerprint matched.
``unreadable``
    the digest could be checked, the routes could not.  The extractor reads
    HTML tables; most cited sources are PDFs.  This is emphatically *not* a
    finding of drift — an empty extraction resembles total turnover, and
    reporting it as such would send someone chasing a change that never
    happened.
``no-routes``
    the evidence pins a digest but records nothing about the page's contents,
    so there is nothing to compare.
``unattested``
    no digest was ever captured; the citation is a URL and a promise.
``fetch-failed``
    the source did not answer.  A 404 means the citation is dead.

A changed digest is reported as ``changed`` and nothing more.  For a PDF
regenerated by a bank's CMS it usually means the bytes moved, not the
settlement instructions; for an HTML table it is the signal to run the
per-file verifier and find out which.  The sweep does not guess, and it
writes nothing: deciding what a change means is the operator's job.

Usage:
    python scripts/ssi-autopilot/sweep_source_attestations.py
    python scripts/ssi-autopilot/sweep_source_attestations.py --json
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import sys
from pathlib import Path
from typing import Callable, Iterable

ROOT = Path(__file__).resolve().parents[2]
EVIDENCE_DIR = ROOT / "scripts/ssi-autopilot/evidence"


def _load_attestation():
    path = Path(__file__).resolve().parent / "verify_source_attestation.py"
    spec = importlib.util.spec_from_file_location("ssi_source_attestation", path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


attestation = _load_attestation()


def _classify(evidence: dict, source_bytes: bytes) -> tuple[str, bool, str]:
    """Return (status, routes_checked, detail) for a source that was fetched."""
    try:
        report = attestation.compare(evidence, source_bytes)
    except SystemExit as exc:
        message = str(exc)
        if "no routes and no route_keys" in message:
            return "no-routes", False, "evidence records no routes"
        return (
            "unreadable",
            False,
            "extractor reads HTML tables; this source is not one",
        )

    if report["fingerprints"]["changed"]:
        moved = [
            f"{route['currency']}/{route['int_bic']}"
            for route in report["fingerprints"]["changed"]
        ]
        return "accounts-changed", True, "accounts moved: " + ", ".join(moved)
    if not report["route_keys"]["match"]:
        keys = report["route_keys"]
        return (
            "routes-changed",
            True,
            f"{keys['actual']} of {keys['expected']} route keys matched",
        )
    return (
        "verified",
        True,
        f"{report['route_keys']['actual']} routes, "
        f"{report['fingerprints']['matched']} fingerprints",
    )


def sweep(
    paths: Iterable[Path],
    fetch: Callable[[str], bytes] | None = None,
) -> list[dict]:
    """Check each evidence file against its cited source.

    `fetch` is injected so the sweep is testable without a network, and so an
    operator can point it at a cache.
    """
    fetcher = fetch or attestation._fetch
    results: list[dict] = []
    for path in paths:
        evidence = json.loads(path.read_text(encoding="utf-8"))
        result = {
            "file": path.name,
            "source": evidence.get("source", ""),
            "digest": "absent",
            "status": "unattested",
            "routes_checked": False,
            "detail": "no source_sha256 was ever captured",
        }
        if "source_sha256" not in evidence:
            results.append(result)
            continue
        try:
            source_bytes = fetcher(evidence["source"])
        except Exception as exc:  # noqa: BLE001 - one dead source must not end the sweep
            result.update(
                digest="unknown",
                status="fetch-failed",
                detail=f"{type(exc).__name__}: {exc}",
            )
            results.append(result)
            continue

        digest = hashlib.sha256(
            attestation._canonical_source_bytes(source_bytes)
        ).hexdigest()
        status, routes_checked, detail = _classify(evidence, source_bytes)
        result.update(
            digest="match" if digest == evidence["source_sha256"] else "changed",
            status=status,
            routes_checked=routes_checked,
            detail=detail,
        )
        results.append(result)
    return results


def _render(results: list[dict]) -> str:
    width = max((len(result["file"]) for result in results), default=4)
    lines = [f"{'file'.ljust(width)}  {'digest':8}  {'status':16}  detail"]
    for result in results:
        lines.append(
            f"{result['file'].ljust(width)}  {result['digest']:8}  "
            f"{result['status']:16}  {result['detail']}"
        )
    tally: dict[str, int] = {}
    for result in results:
        tally[result["status"]] = tally.get(result["status"], 0) + 1
        tally["digest:" + result["digest"]] = tally.get("digest:" + result["digest"], 0) + 1
    lines.append("")
    for key in sorted(tally):
        lines.append(f"  {key:22} {tally[key]}")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--evidence-dir", type=Path, default=EVIDENCE_DIR)
    parser.add_argument("--json", action="store_true", help="emit machine-readable output")
    args = parser.parse_args()

    results = sweep(sorted(args.evidence_dir.glob("*.json")))
    print(json.dumps(results, indent=2) if args.json else _render(results))
    return 0


if __name__ == "__main__":
    sys.exit(main())
